### ISSUE TITLE
Better fleshing out of exploration and survey nodes

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#111]
I'd like to do the following:
- Move manned lander technology into "Advanced Exploration" (currently it's in Space Exploration, along with the 3-person capsules).
- Move SCANsat sensors into Orbital Surveys and Advanced Sensors (these nodes are currently empty).
- Put the DMagic "orbital telescope" (which is really a spy camera, as it's biome-dependent InSpaceLow) into orbital surveys / advanced sensors as well.

This means all these nodes now have value, with surveys providing map and photographic data (for players with appropriate mods), and advanced exploration providing capsules (which leads into rovers in field science).

If players don't have SCANsat or DMagic Orbital Science installed, then the survey/sensor nodes won't appear, but the "Advanced Exploration" node will still have value (right now it's looking pretty weak, and the default parts there are _ladders_).

**Comment by NathanKell** [comment]
This sounds good to me all round. For the longer term, I would support placing DMagic stuff later in the tree, in later science/unmanned nodes, and either using inbuilt probe experiments or cloned or otherwise stolen parts for early variants of those experiments, per our (jeez, months back) discussions of space science.

**Comment by pap1723** [comment]
New Tech Tree in RP-1
