### ISSUE TITLE
Two mission trainings invisible

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#1175]
I recently had a kerbal with two mission trainings: "Gemini" and "Landing" - I could only see the latter (which was the later training the kerbal got), and not the former, even though both were there, and I could enter a gemini capsule. 

Maybe the representation needs some work? 

Also: The "landing " mission training took only like 15min. - This should be longer, shouldn't it? At least two weeks, I'd say.

**Comment by siimav** [comment]
Unfortunately the issue doesn't make it clear which Gemini part you actually used. Might be that it just wasn't correctly configured for the training system yet. I have now added training course names to the RP-1 PartModule that is used for showing the part internal name and ECMs in the part picker menus.

Looks like the "Landing" category has a proficiency training time of 310 days but it completely lacks any configs for mission training. On the other hand I don't really know why landers have a training program at all since all it does is allow assigning crew into the pod during launch. Nobody should be able to launch a LEM with crew inside it anyway.
