### ISSUE TITLE
Science not awarded V 1.8.1 RealAntennas

### ISSUE THREAD

**Issue by EnrageMango** [KSP-RO/RP-0#1316]
When I try to transmit, it only gives me science for 2 of the experiments, even if I wait for it to fully transmit, and then I need to re-transmit the data.

**Comment by DRVeyl** [comment]
Log, please.  What version of RealAntennas?

**Comment by EnrageMango** [comment]
Version 1.2, I'll give you the logs in a second.

**Comment by EnrageMango** [comment]
This is gonna sound stupid, but how do I find the log?

**Comment by DRVeyl** [comment]
It's one folder up from Gamedata. I need a log where the issue occurs, so load up the game, cause the issue, then paste the log here.

**Comment by EnrageMango** [comment]
Got it.

**Comment by EnrageMango** [comment]
Do I need to exit the game to give you the logs? And also the only folder up from Gamedata is CKAN.

**Comment by DRVeyl** [comment]
You don't, no.
I don't know what to tell you about finding where you installed your KSP to, or what Gamedata you are looking at if it isn't a folder in your KSP install.

**Comment by EnrageMango** [comment]
[KSP.log](https://github.com/KSP-RO/RP-0/files/4967732/KSP.log)

**Comment by DRVeyl** [comment]
Ok, I see pressure scan getting awarded, then telemetry getting awarded.  What _should_ I be seeing?

<start of sending science>
[LOG 13:16:28.558] [ModuleRealAntenna]  Setting transmission params: rate: 31.5, interval: 1.0s, rescale: 0.01000, size: 0.315000

[LOG 13:16:45.830] [ModuleRealAntenna]  StockScienceFixer stuffing the last segment of data...
[LOG 13:16:45.832] [Research & Development]: +4.5 data on Pressure Scan while flying over Shores of an Earth. 1 Science added. Subject value is 0.00

[LOG 13:17:05.155] [Research & Development]: +4 data on Telemetry Analysis while flying over Shores of an Earth. 1 Science added. Subject value is 0.00

And your log ends 3 seconds later, with the last entry at:
[LOG 13:17:08.918] [RealAntennasCommNetwork] CommNode walk

**Comment by EnrageMango** [comment]
I sent a temperature scan as well.

**Comment by DRVeyl** [comment]
Thankyou.  I have reproduced the issue and will fix in RA.

**Comment by EnrageMango** [comment]
Thanks!

**Comment by DRVeyl** [comment]
<https://github.com/DRVeyl/RealAntennas/commit/6147199799df7563eaefbdc0b5955e5764d66cba> Will close this issue when RA next releases.  Leaning towards adding some UI improvements first, rather than a hotfix.

What was happening was a combination of bugs: both the stock bug of failing to award science when completing a transmission <https://github.com/DRVeyl/RealAntennas/issues/9 strikes again!> and the protection mechanic I wrote only working for the first transfer.  When you queued multiple, extra instances of the monitoring all worked overtime on the first transfer, ensured it worked, and retired.  Then the next queued transmission started without any monitoring.

As a workaround, if you do not queue the transmissions, but just initiate one and wait for it to complete before initiating the next, you will get all your science, and none of the transmissions should complete without awarding.

**Comment by EnrageMango** [comment]
Hmm, I tried waiting for it to complete, and it still wouldn't work.

**Comment by DRVeyl** [comment]
Believe fixed NLT RealAntennas 1.3 release.
