### ISSUE TITLE
Economy / Strategy / Builds / BIG Ideas

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#1337]
The initial idea of this is to determine if there are viable BIG idea changes that we can put into RP-1 to improve / change how the game is played currently. The first one comes from @leudaimon 

discussion to revamp KCT/the economy... I wrote up a wall of text with my ideas. I know they are very unfeasible, but might be food for thought:
[6:07 AM]
My idea comes as a suggestion to tackle the current problems:

1. The game feels like a race where all you have to do is throw as much money as possible into KCT upgrades. All other design decisions become minor compared with this. 
This becomes obvious when we break up the expenses along the early career at least (up to uncrewed moon landing): 
KCT upgrades account for a huge proportion of expenses, and actual rocket design (launch costs, unlocks and tooling) account for a very small amount. 
More unrealistically, hugely increasing R&D and production incurs very small fixed costs beyond the initial investment.

2. Too much grinding: given the above, you have to keep the VAB working at all times and have to get as much money as possible.

3. There are no meaningful decisions involved in money/resource allocation right now.

My proposed solution is to remove the purchase of KCT points completely, and implement a hybrid contract/"budget" system.
As you will see it is not a real budget.
So, instead of buying KCT points, each contract you accept gives you "manpower" for the duration of the contract instead of advance money. 
This manpower has to be allocated into Production, R&D and commercial contracts (later on I'll suggest a complication on this, but it's not necessary for the argument). 
You will have this manpower immediately, and it will last at full force until the contract deadline, even if you complete it earlier. Once the deadline is over, it fades away smoothly.
Not all contracts would have this manpower advance though, the contracts we currently have that work as commercial contracts (mainly payload contracts) wouldn't give you additional manpower.
[6:07 AM]
So, how would this manpower work: you allocate it into the 3 (or four, see later on) "buckets", and how much each "point" of manpower generates in Producion/R&D/Money is given by the facility level of the R&D/VAB/SPH for R&D and Production. We could then have more levels of these facilities, and blocked by bluesky nodes (material science for production, electronics for R&D). 
For the commercial manpower, I think we could have some of the current payload contracts working as triggers to increase the yield of commercial manpower. So then you don't need to crank out a lot of filler contract launches, just a few whenever you feel you have more cappability and would like to increase the yield of your commercial manpower. Commercial manpower would give some kind of budget, maybe every month or quarter.
Also, this could still work with the sliders we were discussing, where you can change the allocation of this manpower even if you are not getting a new contract, either at a cost or some delay, but I think in a way, this change in manpower you get every time a new contract is accepted/another is expiring would help keeping things flexible even without a slider.

Still, most of your money is supposed to come from rewards from the contracts you do complete, and as you are not pressed to buy all the KCT points, some of this money can go into flights that not necessarily give you money, but will bring additional science, or flight testing a rocket (and of course the other current expenses - facility upgrades, tooling, unlocking etc.). 
Also, as the manpower ramp up you get from accepting contracts lasts for a fixed time instead of being permanent, there is less snowballing on one side, and people that wait until they are capable of completing a contract to accept it do not lose much, as they will have this increased capacity for a longer time later.(edited)
[6:07 AM]
I think this would allow for a variety of gameplay, as you can invest in commercial to different degrees, push R&D vs. production at different levels, and gives more flexibility for people to do things that not necessarily give money immediately, but bring science or other benefits. Also, it makes it so that you are only capable of production if you have long-term goes set, in the form of the contracts you accepted that give manpower.

Now, about a possible fourth "bucket" for manpower: how about we include tooling and part unlocking as something that needs to be completed as well? It would induce the decision on whether you want high production capacity using the parts/sizes you already have vs. directing manpower into developing new designs. 
This way, any new tooling you make or part you unlock would enter a new queue in addition to production and R&D to be completed. Given right now tooling is a non-decision (you always do it), I would make tooling mandatory, and you can only produce a rocket with already tooled parts. 
This idea is not necessary for the rest to work, but I think it introduces interesting trade-offs.

I'm fully aware this requires a total revamp of KCT (and the contract system a bit), but thinking freely from the system we currently have, I think this would bring very interesting gameplay.

**Comment by Rounan** [comment]
I couldn't agree more with Maxsimal. Before addressing the "balance" between dawdling newbies, normal play, extreme min-maxers and Maxsimal/LPG insanity... we need to be able to define those.

I think having only one currency in the game is the root of many intractable balance problems. That currency, ATM, is KCT upgrade points. That's the real thing that drives progression. the purpose of funds is to buy points and facilities, building and launching rockets is a rounding error. the purpose of science is to buy research but there's so much available it's not a real limit; instead its biggest impact of collecting more science in-game is to buy you upgrade points.

This is why, IMHO, it's so difficult to balance "repeatables" without encouraging grind - if funds make you go faster, then grinding funds is optimal, always. Only question is which contract will give me the most money today, and "optimal play" will fall in a very narrow band.

If you want to control progression rate independently of money... why not have research rate determined by a totally separate currency or system, with no conversion method? Just spitballing, you could tie research rate to game progression by awarding a new currency for bluesky node completion. that currency is used only to purchase R&D points, and so these purchase happen automatically - doesn't even need to be user-facing since no decisions need be made. Just increase rates by some amount for each bluesky node, likely at a slightly-faster exponential rate than the research costs rise per node.

Under that model, R&D speed is very consistent across playthroughs, with only minor variations from some minmaxers rushing blueskies at the expense of real useful tech. You'd have a solid sense at design time of how long it would take in-game to research each node. Any balance tweaks would affect this directly, for all players regardless of their tactics.

Balancing funds rewards would be much easier if they couldn't be dumped into R&D points. Fix the snowball by starving it of snow.

**Comment by FrisbeeDriver** [comment]
One system that is not a total departure from the current system that seemed to work pretty well was the Quarterly Budget mod that modified the RP-1 contract system.  NQB tweaked the contracts to make use of the reputation points.  The more reputation the more money that you got each quarter.  The reputation would fade off over time requiring you to keep dong things to keep your reputation growing otherwise your budgets would start to shrink.

**Comment by marsh1832** [comment]
I agree with the general idea of quarterly budget, but there are simpler ways of accomplishing the same goal using reputation. For example, we already have essentially three types of contracts/missions. 1: Milestone contracts with big payouts that advance the career. 2: Science missions primarily to advance tech 3: Money making repeatables

I think the last two are fairly balanced as is, you make choices based on what your program needs at the time. The thing that’s out of place is the big milestone missions. They’re worth so much, and you earn enormous amounts of money with advances. In fact we accept them more for the advances than the payout... isn’t that a little weird?

How about lowering the pay of all of the milestone contracts so they are in line with other contracts? Instead milestone contracts, on first completion, pay a huge chunk of reputation which in turn makes future contacts pay more. If they are repeatable, the money pays the same but the rep bonus is much less.

So with each mission you chose to do, (be a contract or not) you’re deciding between reputation, science, or funds, depending on what you need.

I still think KCT points need some kind of overhaul, such as a progressive increase in cost per each new point purchase, or a hard cap that is unlocked with science, reputation, or both.

**Comment by Arodoid** [comment]
> What would this look like:
> The spreadsheet would list different eras of rocketry.
> It would list in each era where the player would invest thier resources - unlocks, tooling, etc, as ballpark %'s.
> It would list what accomplishments the player was expected to complete, in terms of milestones. How many launches they were expected to make to get there.
> It would list, where the expectation for the player to be at, in terms of science unlocked, biomes explored, etc.

I know this issue is old but it's late and I have some thoughts.

One thing that always irked me from the beginning of playing rp-0 many years ago is that it always felt more like historical progression-0 than realistic progression-0. That might sound stupid, but my point is the contract system, tech tree and progression as a whole always felt like it was trying to keep you on track with history by forcing you to recreate it rather than letting you recreate it. It doesn't feel very dynamic. Almost all of the BIG idea changes in github consist of ideas that would expand the creativity of the player. Except the very idea of a creative player contradicts rp-0's current layout of having an "on rails" historical progression. With that being said...

I know this is insane and impossible and would require a complete redo of almost all of rp-1/RO but, I think it would be amazing to start with literally nothing, no engines, no capsules, no contracts, nothing pre configured, ect.. Everything would be researched and designed by the player. Engines would be researched and developed, contracts would be conjured up be a "team". EVERYTHING would have to be procedural and toolable, capsules, cockpits, engines, station parts, everything. The tech tree would need to be completely stripped of any ideas of "eras". A tech tree might not even be the way to do it, it may not be dynamic and free flowing enough.

Imagine the feeling of looking back at your career and thinking: "huh, this seems pretty historical.", while rp-0 never made you do any of it. I think it would lead to many amazing "ah ha" moments like "Oh that's why Gemini did it that way".

In the end I'm just a dude who doesn't know how 99% of this shit works. I can play my rp-2 in my dreams I guess...

**Comment by Arodoid** [comment]
To add a bit to this.
Current rp-1 and stock career feels like I'm playing in a creepy dead world, working as a contractor for some deity giving my monkey dollars. I want to feel more alive.  Where are the consequences for not hitting milestones on time? (or possible benefits... _For All Man Kind_). Where are the other space programs? I want decisions to matter more. The only major career decisions I feel like I make in game are "is it too early to accept this contract" and "is this design good enough to complete the contract" and "have I allocated the contract money in the right places? building upgrades, KCT, and entry costs and saving for later"

**Comment by siimav** [comment]
Something something Programs.
