### ISSUE TITLE
Error in Loading KCT Data

### ISSUE THREAD

**Issue by Peter-JY** [KSP-RO/RP-0#1421]
KCT reported a error and need I to send "KSP.log" to here. It said that this bug will make things "seriously broken".

In Start Menu:
“Incorrect Kerbal Construction Time Installation
Kerbal Construction Time has been installed incorrectly and will not function properly. KCT is now integrated into RP-1 which means that installing it as a separate mod is no longer allowed.
Incorrect path(s):
GameData\KerbalConstructionTime\Plugins\KerbalConstruction.dll”

In Game:
"Error Loading KCT Data
ERROR! An error occurred while loading KCT data. Things will be seriously broken! Please report this error to RP-1 Github and attach the log file. The game will be UNPLAYBALE in this state."

[issues in KCT Github page](https://github.com/linuxgurugamer/KCT/issues/81)
[KSP.log](https://drive.google.com/drive/folders/1CRF7Vnx7mS00I4GunpDQaU9r-GyBDbTp?usp=sharing)

Game Version: 1.8.1 (build id 02694) with all DLCs

**Comment by siimav** [comment]
As the message says - KCT is now distributed together with RP-1/0 itself. This means that you will need to delete the `GameData\KerbalConstructionTime` folder.

**Comment by Peter-JY** [comment]
But is there any time that we can disable KCT in sandbox game? Or in KRASH?

**Comment by siimav** [comment]
Huh?

**Comment by Peter-JY** [comment]
hmmm......Can I speak in Chinese? (Chinese is my mother language)
我的意思是说，请问能在RP-1里关掉KCT吗？比如说我不想非常麻烦的去删除Mod，而直接新建一个sandbox存档，这个存档能否不受KCT的影响(也就是建造火箭是否还需等待)？如果在career存档中使用KRASH这个模拟Mod，也会受到KCT的影响吗？

**Comment by Bornholio** [comment]
hmmm......Can I speak in Chinese? (Chinese is my mother language) **可以，但是我的中文很粗糙**
I mean, can I turn off KCT in RP-1? For example, I don't want to be troublesome to delete the mod, but create a new sandbox archive. Can this archive be free from the influence of KCT (that is, do I need to wait for the rocket to be built)? If I use KRASH as a simulation mod in the career archive, will it be affected by KCT? **是**

In addition, I’m sorry to trouble you to answer my worthless issues because I didn’t understand the series of error reports in English. **很好，我们都热爱太空和KSP**

**you may want to make separate installs, as simple as copy the whole game to a new folder.
您可能需要进行单独的安装，就像将整个游戏复制到新文件夹一样简单**。

**Comment by Teykn** [comment]
KRASH as a simulation mod is not affected by KCT. KCT only affects things that need to be **built**. Simulations do not fall under that.

In Sandbox, I don't think there's a way to disable it, sadly. However, if you plan on doing Sandbox, it'd be better to have a separate install that has RO **only**, since RO does not include KCT; only RP-1 does.

**Comment by kapacity** [comment]
There is way to disable it:
![Inkedscreenshot3_LI](https://user-images.githubusercontent.com/59689707/104033068-53be6980-51cf-11eb-920d-b81d115c6aac.png)
![Inkedscreenshot4_LI](https://user-images.githubusercontent.com/59689707/104033069-54570000-51cf-11eb-9d90-51d7c4cd14e3.png)

**Comment by jwvanderbeck** [comment]
You CAN disable it but at that point you are not really playing RP1 anymore.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by Peter-JY** [comment]
I’m very grateful to everyone for helping me so enthusiastically, and now my problem has been solved. Thank for everyone again.
