### ISSUE TITLE
Agena equipment rack has negative BP cost if electric battery is removed from it.

### ISSUE THREAD

**Issue by sohmien** [KSP-RO/RP-0#1654]
![screenshot1](https://user-images.githubusercontent.com/76263529/144501417-68000431-12e6-447b-b829-d1d1d8cf0273.png)

**Comment by siimav** [comment]
@Capkirk123 you were working on something that would resolve this?

**Comment by Capkirk123** [comment]
This is actually just an issue with KER. The part does not actually get negative mass, or, in fact, change mass at all when the batteries are removed.

This fact is also an issue (and my experiments in converting preset parts to use tank masses instead of fixed masses would fix it), but unrelated and much more minor.
