### ISSUE TITLE
cost recovery

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#186]
even if I land directly near KSC, I get a 300km distance reported and receive only 80-something percent. - It'S only a very minor nuisance, but maybe easy to fix?

**Comment by NathanKell** [comment]
That's...weird. Sounds like a Kopernicus bug though I thought we had that fixed loooong ago. Tbh I don't pay much attention to recovery amounts since the hardware wouldn't (IRL) be reused anyway, so I must not have noticed.

**Comment by NathanKell** [comment]
Wait a sec. Maybe something in a recent Kopernicus broke it, and I haven't noticed? For a while I was still on beta 1, only last few days did I update to the current version and I haven't paid attention to recovery since.

**Comment by NathanKell** [comment]
And @glilienthal  thank you for all these! Super helpful :)

**Comment by glilienthal** [comment]
nice to hear the encouragement. I'll bring more. - And if the bug reports are not complete enough, just ask. :)

**Comment by NathanKell** [comment]
Please do! I played through human orbit to verify everything worked (and fixed what I found) but I obviously missed a lot. ^_^

So far the reports are giving me enough to go on, but in general if you can zip and post a player.log (output_log.txt) from after the bug evidencing itself that can help. Because it's possible there's an interference issue, or something's randomly throwing, or something.

**Comment by NathanKell** [comment]
Sorry, lost net access and got busy. Back now. Will get to this (again).
