### ISSUE TITLE
Staging spent boosters containing avionics shuts down all engines.

### ISSUE THREAD

**Issue by SirKeplan** [KSP-RO/RP-0#192]
To test, make a craft with an early guidance unit, fuel tank, and engine. add 2 radially attached liquid boosters, making sure they have avionics too. start all the engines and wait for the boosters to burn out. exactly when you stage the boosters the core engine will automatically shut down.

KSP.log
https://www.dropbox.com/s/ysb6iyq8bm4f88j/KSP_engine_shutdown.log?dl=0
Player.log
https://www.dropbox.com/s/1ejxybjwwcmv54k/Player_engine_shutdown.log?dl=0

**Comment by Schnobs** [comment]
Ditching the part that's currently controlling the vessel is regular cause for trouble; you can have that in stock as well.

Toggling SAS / MJ off and on after staging usually puts things in order, but of course it won't restart your engines. Sometimes it helps to select the proper command module ahead of time and do a "control from here", sometimes it doesn't.

**Comment by NathanKell** [comment]
@SirKeplan are you controlling from one of them, or from the core itself?

**Comment by SirKeplan** [comment]
Obviously controlling from the core. If the core has a restartable engine, then it just uses up 1 ignition, otherwise core shuts down with a message saying no ignitions remaining.

**Comment by Schnobs** [comment]
Just want to confirm that yes, I'm having that as well.

Maybe related: MJ's smartass lets go of the vessel at the same time. It doesn't change appearance, but won't issue any control commands (pitch/yaw/roll indicators in the corner remain centered) until one turns it "off" and on again.

My own advice of controlling from the final core in the stack didn't help. This always and reliably happens when I ditch a command module.

**Comment by NathanKell** [comment]
This is actually a RemoteTech issue. On staging, the antenna network is recreated, and for some reason on the first tick it counts as no connection, so throttle is set to 0.

RT really, really, *really* needs an option to toggle zeroing throttle on no connection; it should be toggleable between zeroing throttle, and retaining old state throttle. @Peppie23 is that something you could add?

**Comment by Peppie23** [comment]
Sure, i'll look into the option to keep the throttle on no connection (http://github.com/RemoteTechnologiesGroup/RemoteTech/issues/245)

But for this, can someone give me a craft how i can reproduce this issue?

**Comment by SirKeplan** [comment]
i just whipped up a .craft
https://www.dropbox.com/s/us9au3livzcrhss/StagingDisconnect.craft?dl=0
I've just realised the craft may may require FASA though.

**Comment by NathanKell** [comment]
Presumably also Realism Overhaul and RealFuels.

@Peppie23 the issue is that (a) in RO we give avionics rings passive antennas, and (b) RealFuels gives engines limited ignitions and considers an engine unignited when throttle goes to 0. To repro you can probably do it with probe cores, but you'll need some plugin that reports whenever ctrlstate.throttle goes to 0, unless you want to have RF + RO installed.

**Comment by Peppie23** [comment]
@NathanKell yep thanks. I know about your ignition system in RSS (RP-0).

So, i've disabled the option for throttling back to zero on no connection but the "issue" still exists. I also have problems with sounding rockets like:

![test-2](https://cloud.githubusercontent.com/assets/7722222/9769623/8ddca806-572b-11e5-874b-6b6aa586a15e.jpg)

if i stage the aerobee before staging the clamp, so i 've to investigate a bit more.

**Comment by Peppie23** [comment]
@SirKeplan you can use the dev-build https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/build-develop-422 for cross-checking this issue.
Please do these steps before testing:
- download the devbuild and replace your current remotetech folder
- start ksp with any save you want and go to the tracking station (to create the RemoteTech_Settings.cfg)
- close ksp
- open the RemoteTech_Settings.cfg and change this line: `ThrottleZeroOnNoConnection = True` to `ThrottleZeroOnNoConnection = False`
- start ksp again and check this issue

@NathanKell later this day (or tomorrow) i'll create a pull request in RO to change your RTSettings file to set this value per default to `False`

**Comment by SirKeplan** [comment]
@Peppie23 Thanks! that seems to solve the issue.

Only thing is starting KSP(with RO and RP-0 etc) didn't modify/create any RemoteTech_Settings.cfg file for me, so i added the line manually and it fixed the issue.

**Comment by Schnobs** [comment]
Coming late, but... there's at least one more case where the throttle gets momentarily zeroed: I like to start my burns myself because MJ doesn't know about ullage. If during the burn I want to pass control to Mechjeb ("execute next node"), this will eat one ignition.

Of course, the best solution would be if MJ would take care of ullage. Barring that, I'd like engines to re-ignite at no cost if they've only been shut down for a very brief moment. While kludgy, that would be a generice kludge covering many use cases.
