### ISSUE TITLE
US Probes RO Balance issues

### ISSUE THREAD

**Issue by droric** [KSP-RO/RP-0#209]
Solar panels may need a balance pass
additional Science Experiments need to be added
Antenna range is low for interplanetary probes

US Probes spreadsheet found here: https://docs.google.com/spreadsheets/d/1nSpgjnR8j-CoM71H5H9RJS2xfRVuKFtgeVRqiMn419k/edit?usp=sharing

Fixed: Some probes (Pioneer 5, more?) have the ability to perform crew reports.  
Fixed: The US Probes by Raidernick seem to bypass the need for avionics on a vessel.  They lack avionics but have command: unmanned.  -- Avionics have been added.

**Comment by NathanKell** [comment]
Ah, the crew reports are because of a typo here:
https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Science/PartExperimentAdder.cfg#L21

For avionics, entries need to be added to https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Avionics.cfg for each of the probes (or for multiple ones at once if they should share the same max-mass).

The solar panels' charge rates should be based on the actual charge rates achieved by the probes in use. That's fairly hard to find for some so we can make assumptions, but I would expect, say, the early Vanguards to have <100W / m^2.

**Comment by droric** [comment]
Added Avionics in my last pull request.  Might look into solar panel power next or something else...

**Comment by NathanKell** [comment]
Sounds good!

**Comment by droric** [comment]
Sent out an Explorer-6 today to do some local exploring outside Earth's SOI.  I quickly lost control of the probe with the included configs.  The range in this file seems more appropriate for RSS given these are interplanetary probes.  The cfg was found on http://forum.kerbalspaceprogram.com/threads/93389-1-0-2-US-Probes-Pack-Old-and-New-v0-33-5-Release-5-10-15.  Can this be included or are there licensing issues?  It uses ModuleRTAntennaPassive which is different than the other configs though...

https://www.mediafire.com/?97yducwjlcbi435

**Comment by NathanKell** [comment]
With the wrong experiments removed, now we need to add the *right* experiments. Hopefully your research turned up what instruments were on these probes, at least the early ones (i.e. the ones where we already have the experiments, mostly)?

**Comment by droric** [comment]
I'll be all over this tonight when I get home.  I have a short list of things I want to try to take a look at tonight and this is one of them.  I can't wait till KSP 1.1 is released.  I can't get used to not having native access to OneNote/Notepad++/VisualStudio/3dsmax in my Linux install.

**Comment by NathanKell** [comment]
Awesome! :)

Swap OneNote for Photoshop and you have my exact reason for no linux install, too. :] I feel ya.
