### ISSUE TITLE
Proc SRB cost

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#212]
Something's screwy, at least for Tyler.

**Comment by BevoLJ** [comment]
But I spent all 50k already! =D  Ya, the Proc SRBs are crazy underpowered.  Even after spending all that cash for them, they just are not good. Quite horrible actually. I wanted to use them very badly since I spent all that money, but just can't think of any situation in which they would be more useful than the RL version of kickers/boosters we have.

**Comment by BevoLJ** [comment]
One other thing I noticed, after unlocking Mature SRB science node, I can upgrade my PP SRB in surface mode to level 2, and vacuum mode to level one. This makes the surface mode better for space than the vac mode.

**Comment by NathanKell** [comment]
Solid fuel costs are still whack. Fixed in RO 10.4.1 (forthcoming). I'll fix the techlevels, great catch!
