### ISSUE TITLE
Tech tree overhaul and state funding

### ISSUE THREAD

**Issue by Niemand303** [KSP-RO/RP-0#224]
## Tech Tree

It's no secret that apart from propulsion and probes the tech tree in RP-0 is really strong WIP with lots of empty and weirdly placed nodes. At the moment I'm working on my own tech tree variant for RP-0, more compact but offering same amount of choices.

[Here is the PNG](http://i.imgur.com/CaG6hrb.png) of the yet _unfinsihed_ tree itself, and I can post the .dia diagram file if needed to get a better understanding of node interconnections.

![Tech Tree](http://i.imgur.com/CaG6hrb.png)

White nodes are those left unchanged from the existing tree, red -- edited ones, green -- completely new nodes. I post it unfinished to take into consideration any suggestion that might appear.
## State funding

As a second suggestion, I'd consider having a specific "contract/mission set" to simulate the state funding as it happened in USSR, for instance. I'm not sure if that was suggested before, but I think it's possible to make using existing contract mechanics.

**Comment by NathanKell** [comment]
As I said on IRC I love those changes!

One note on them, regarding the dashed lines. I'm taking that to be "any node unlocks"? In which case I should mention that RP-0's policy thus far has been to not have "any node unlocks" nodes; that some crept through were my failure in forgetting to patch them. Landing is a good example, it absolutely should depend on both nodes (and I think I fixed this in git, I should check).

Regarding State Funding: there's actually the great State Funding mod, and indeed for the US it was pretty much all state funding too, except with some "cost shares" by the late 60s for comm sats and the like, and then STS launching commercial birds too (but very subsidized). What might make more sense is to do a full overhaul, taking advantage of all the work that the State Funding (or whatever its name) mod does, and basing funding off reputation and goals met and goals expected.

**Comment by Niemand303** [comment]
@NathanKell , good commentary! Regarding "any" politics it might be tricky. Especially when it comes to landing example. Maybe you know that the first Lunar landing probes (Luna-9 and Luna-10) were basically sturdy spheres that fell down on the surface with the powered descent stopping relatively long before the touchdown. I thought that it could reflect such difference in approach with early Luna and Surveyors. But I can see the point in having "all" policy too, so I guess I'm going to go with it.

I like the idea of adding another mod to the "constellation" that is forming RO/RP-0, so I guess I can look into how it works. Also, soon I'm going to upload the finished and polished version of the tech tree, but I have little-to-no idea on how to convert it into game format itself. If you could point out on how it is made in RP-0 I would be very grateful.

**Comment by Niemand303** [comment]
Here is the final version:

![Tech Tree](http://i.imgur.com/kytlpNP.png)

**Comment by NathanKell** [comment]
@Niemand303 let me take a look at that! :)

As to the text, for Luna 9 I based off the wiki entry which described running verniers (and maintaining 3-axis stability, one assumes) until only 5m above the surface, which I had taken to mean requiring Flight Control (and because the vernier that unlocks in Landing itself depends on the RCS tech in Flight Control).

It's certainly possible to make lunar landings without the Landing node (i.e. solid retro plus 1kN thrusters that blip for throttling), and perhaps Luna 9 is best represented as that.

**Comment by NathanKell** [comment]
I really, really, *really* like this tree. Excellent work @Niemand303 ! <3

**Comment by winged7** [comment]
What will happen to parts which are already placed in the nodes you're planning to delete? Will I need to place them again?

for example:  AdvLanding (line 2411 in tree.yml)

**Comment by batuhantasli** [comment]
@Niemand303 This is fantastic. If you haven't started to write this new tree yet maybe I can do it in my free time, or help you if you have started.

@NathanKell If it won't be a big deal, I think it would be nice to change node names appropriately for a clear code. For example basicRocketry to earlyOrbitalRocketry and so on. I know that means changing tree.yml and some other engine config files etc but I think I can do that.

Also, currently there are some parts that affects balance of tech tree IMO. That might require changing early tech tree nodes' links, so I want to write those under this issue. For example, R7 Sputnik tanks are placed in early avionics because they contain 280 tons avionics. However, that means if you have RN R7 or TantaresLV installed you can gain access to 280 tons avionics without unlocking basic avionics and launch into orbit easily by unlocking basic orbital rocketry only while other players should also unlock basic avionics for 120 tons 2m avionics at least. Or, if you have FASA installed, you can unlock basic construction and gain access to Mercury - Atlas LV tank which has 120 tons avionics and that node doesn't require you to unlock basic avionics. Maybe we should place those tanks in basic construction node as they should be and make that node require basic avionics unlocked? Or do you have any other solution in your mind?

**Comment by stratochief66** [comment]
bump. a great topic, unfortunately NathanKell currently seems very busy, hopefully he will have a chance to chew on this sometime soon.

batuhantasli, it sounds like you really know the bugs/exploits in the RP-0 tech tree. I think moving the Atlas tanks as you suggested makes sense to remove that avionics exploit. If avionics part(s) were a bit more flexible than they currently are (NathanKell has mentioned a few ideas for pseudo-procedural avionics) I would say that tanks like the Atlas or R7 should just not have avionics built in.

I probably put both of those exploits in accidentally, as I didn't have a very wide understanding of RP-0 or avionics when I was working on those parts.

**Comment by PhineasFreak** [comment]
Could Strategia be adapted to the State Funding role?

**Comment by SirKeplan** [comment]
I would suggest Moving the ISRU nodes back about 2 Tiers, so Early ISRU would be in the mid of Tier 7, and Basic ISRU would be maybe straddling Tier 7 and 8. possibly have Early ISRU follow on from recycling/'short term habitation'.

This is more inline with what was quite possible, especially looking at Mars Direct.

**Comment by SirKeplan** [comment]
I think "Closed cycle hydrolox" should be renamed to something else. Closed cycle hydrolox engines actually came along earlier than that.

**Comment by NathanKell** [comment]
@SirKeplan: um, which? I mean by this staged combustion--was there a staged combustion hydrolox engine before the 1970s? (Closed cycle has *sometimes* been used to refer to the expander cycle, so maybe we should rename the node).

**Comment by SirKeplan** [comment]
@NathanKell ah sorry, i was intending to clarify my comment, yeah, "Closed-Cycle Hydrolox" is the 4th Hydrolox node in this tree. The first Soviet Hydrolox engines were staged combustion(KVD1, RD-57), these were intended for the N-1, but came along a little late. The KVD1 is placed in the 3rd Hydrolox node currently

**Comment by pap1723** [comment]
I used a lot of this with the design of the new tree. Great work!
