### ISSUE TITLE
stock Mk2, Mk3 tanks - pricing

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RP-0#345]
I just noticed that stock Mk2, Mk3 tanks already have proper prices (compared to procedural ones) so is there any way to mark them as "costed by RP-0" without actually pricing them?.

**Comment by NathanKell** [comment]
Not easily, it's safer (and IMO better practice) to price them in the tree, that keeps all pricing information centralized.

You could set RP0conf = true manually of course (I do it for a few weird items) but per above IMO it's better practice not to.

This is particularly the case since KCT supports launch costs now, and I plan to do a cost rework at some point.

**Comment by winged7** [comment]
But they shouldn't have fixed prices because cost of the tank depends on what is inside the tank.

For example lets grab 100kL tank and fill it with liquid hydrogen. It will cost 2200. Then remove LH2 and change to kerosene - now empty tank will be a couple of times cheaper.

So I'm planning to left it as it is without any pricing.

**Comment by NathanKell** [comment]
Oh, they certainly shouldn't have _fixed_ pricing. But they should have a base price (plus the cost RF adds), and they _certainly_ should have an entryCost which reflects the cost of the shielding.

**Comment by stratochief66** [comment]
@winged7 poke, is this done?

**Comment by winged7** [comment]
@stratochief66 no :>

**Comment by pap1723** [comment]
RP-1 New Costs
