### ISSUE TITLE
KCT integration

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#36]
In #35 Felger mentioned KCT, and also in https://github.com/magico13/KCT/issues/17 @magico13 asked what we're looking for. Thus I'm opening this issue so we can brainstorm what additions/changes/etc to KCT we're looking for.

We've tossed around the idea of manufacturing cost being different from launch cost. That's something to consider, with perhaps multipliers for "payload has never flown", "crewed mission," etc. Further, KCT can handle integration costs, and per-launch infrastructure costs (per-pad infrastructure costs would, I guess, wait for 0.90).

@magico13 has already (thanks so much!) added support for RSS's multiple launch sites, and for configurable time per science point (to unlock nodes).

Other thoughts:
- Time to unlock parts (Development, as well as research, takes time).
- Deep integration with PP (the idea of stretches and propellant changes requiring very little money and time, whereas diameter changes need new tooling)
- Recognizing subassemblies (an oft-used upper stage is far cheaper and faster than a hand-built one)
- Manufacturing lines (say you want to pay a sum in time and money to set up a manufacturing line for a sub-assembly; you then get, say, one stage [subassembly] every few months). You can expand the line, or freeze it, as time goes on costs go down, minor changes don't require new lines, etc.

Further thoughts?

**Comment by magico13** [comment]
I was talking to the developer of [TestFlight](http://forum.kerbalspaceprogram.com/threads/88187-0-90-TestFlight-0-2-1-03JAN15-A-configurable-extensible-parts-research-reliability-system) about whether we should have any sort of integration between it and KCT, and it got me thinking that I should probably start working on an API at some point. I figured I'd drop in here and [post a link to the GitHub issue](https://github.com/magico13/KCT/issues/33) I opened for it, since I don't know if there's anything you guys would want or need from it.

I still have some things I should do regarding RP-0, primarily regarding Procedural Parts handling and adding unlock times for individual parts in tech nodes. I am working on time requirements for KSC upgrades and repairs. Also, when I get around to reworking the settings to use presets, I'll make sure to make it simple for RO to overwrite the settings without worrying about overwriting anyone's custom settings (you'll just provide a presets file for RO. If you update it, anyone using the preset will be updated accordingly. If they change anything then their settings will remain as-is. Other presets won't be affected.) That will also ensure CKAN won't freak out about overwriting any files if they're got KCT configs already on their systems.

**Comment by BevoLJ** [comment]
@magico13 Might it be at all possible to add more launch pads?  IRL a launch site can have more than one, and I really would prefer not having to use multiple launch sites for when interplanetary transfer windows are open as where I launch from is pretty important in my mission planning.  Like it wouldn't need to be something that shows up at the space center, but just something to help us deal with the launch pad repairs.  Typically repairing a launch pad makes it very hard to do multiple missions while transfer windows are open.

**Comment by magico13** [comment]
@BevoLJ  I realize I'm responding to this waaay late, sorry about that. I do plan on additional launch pads, but with RSS you can just launch from different sites already. At the moment it's not a big priority, but if/when I get around to Kerbal Konstructs compatibility then the necessary changes for having multiple launchpads per site will be in place.



Now, for the actual reason I'm posting here. I just committed a change that you guys are probably going to love and I figured I'd give you a heads up since I'm planning on making the changes official soon after a period of bug testing. Basically, I just made it so that you can define *precisely* how build points are calculated *in the KCT_Formulas.cfg file*. So you guys (or the user) will have (near) total control over how things are calculated. It uses the same variable and math system as the other things in that file, but the number of variables available for BP calculations is a bit higher.

I'll try to give a basic rundown. There's a few other important changes that I'll highlight at the end of this post.

So, KCT has two stages to BP calculation: 1) calculate an "effective cost" of a part by taking the cost and doing some stuff based on if it's in the inventory and how many times it's been used, and 2) take the sum of the effective costs of all the parts and do a bit more manipulation on it. Those two stages still exist, but you can define the formulas used for them. The "effective cost" has two variants, the normal "EffectivePartFormula" and the one for procedural parts called "ProceduralPartFormula".

**EffectivePartFormula:**
Variables available (must wrap in square brackets): C=cost, M=wet mass, m=dry mass, U=part tracker, O=overall multiplier, I=inventory effect (0 if not in inv), B=build effect

Note: O, I, and B are the normal time settings that go by the same name.

Default:  "min([C]/([I] + ([B]*([U]+1))), [C])"

**ProceduralPartFormula:**

Variables: C=cost, A=cost covered by inv, M=wet mass, m=dry mass, U=part tracker, O=overall multiplier, I=inventory effect (0 if not in inv), B=build effect

"A" is a bit different here. Since the inventory for procedural parts is handled differently (the amount is part cost * 1000), A is the amount in the inventory divided by 1000, or the part cost, whichever is lower. It's used to calculate how much "material" is available to be reused.

Default: "(([C]-[A]) + ([A]*10/max([I],1))) / max([B]*([U]+1),1)"

**The final part is the final BP calculation:**

Variables: E=total effective cost, O=overall multiplier

Default: "([E]^(1/2))*2000*[O]"



Additional notes: You may have noticed the use of min(x,y) and max(x,y) in those formulas. I've added a few functions to the math parser. "l(x)" (lower case L) is the natural log, "L(x)" is the log base 10, "min(x,y)" will take the minimum of two values, and "max(x,y)" will take the maximum of two values. There are a few formatting restrictions to these that you should be aware of though. They MUST have parenthesis following them and cannot have spaces between the command and the parenthesis [ie, "min (x,y)" == bad, "min( x, y )" == good]. Spaces inside the parenthesis are fine. They are case sensitive, so you can't use "Max", you have to use "max". You can (theoretically) nest a min inside a max, or vice versa, but must put the nested function in the second slot (I need to verify this). It's a side effect of how it detects the comma. So "min(x, max(y, z))" should work as expected, but "min(max(y,z), x)" won't work. Like I said, I haven't tested that yet.

As a result of this, I've removed the "UpgradeFundsMax" and other similar settings since you can just use the min() function to achieve the same thing. **You'll want to update accordingly.**

It's possible I've missed a thing or two, or that the formatting/my generally dispersed mind has made this unintelligible. If you need any assistance/have questions don't hesitate to ask. Hopefully you guys find the changes helpful! I've also fixed some other bugs and made a few changes (like adding time requirements to KSC upgrades) in the dev builds. I have a few more functions that I should open up (like the KSC upgrade one) at some point as well, but I may release without them unless you guys want them ASAP.

**Comment by NathanKell** [comment]
@magico13 that's awesome!

**Comment by pap1723** [comment]
KCT now supports all of this.
