### ISSUE TITLE
RP-0 FASA Tuning

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RP-0#407]
@NathanKell 

Some opinion from you (and others) is desired. Doing a bit or research (bnumz) I find that the Titan 3A and Titan 3C were launched first in 1964 and 1965 with the trans-stage (AJ10-138). I believe this means it should fall within the TL2 period (?) and therefore could be placed in 'Mature Orbital'. Does this sound right?

Those craft will also require the Titan 3 first stage tank, which I was thinking would be placed in 'General Construction' (?)

I am just trying to tune things up to the Saturn IB, so far my 'basically pure FASA RP-0 playthrough' has been going swimmingly.

I have noticed a few future things that might need moving. For instance, the Nova first and second stage are in "Advanced Construction", which is in TL3 (1965 through end of Apollo?) while I believe they would make sense to be moved to "Specialized Construction"?

Currently, 10m proc parts only become available in SpecCon, while AdvCon (apollo era, TL3?) only gives access to 7m. Should these perhaps be bumped earlier a bit, to match the era and FASA parts that are available, or the other way around? Possibly adding an in-between node to help fill the gap might make sense?

Another alternative, they could all stay where they are, but the Saturn V first and second stage tankage could have a fairly high entry cost, representing the Apollo level investment required to jump to that tankage size? That has the disadvantage of making that tankage unavailable (at any cost) to people not using FASA or other mods with replica tanks.

An interesting (but complex) idea might be to have a tank size that is available at an unlock (ie. 7m) at a reasonable (ie. current) price, while up to ~30% larger is available at a serious premium (until the next proc unlock is researched)? Probably too complex to code for now, but possibly an interesting mechanic.

Saturn V tanks also need pricing (currently S-IVb tankage is more expensive)

**Comment by stratochief66** [comment]
Ahh, also just noticed that the LR87-9 isn't unlocked in game until heavyRocketry (Heavy Orbital Rocketry):
https://github.com/KSP-RO/RP-0/blob/8a2025dab408f21dc31265b360b1e2dbdf553f33/GameData/RP-0/FASA_Engines.cfg#L32

It is used on the Titan 3A in 1964, which I believe should place it the same as the -5 and -7 variants (?)

**Comment by stratochief66** [comment]
I'm unsure what causes, this but it is a bit glitchy. The S-II stage tank and engine mount part FASAApalloLFTJ25XPlate reports a cost of 400 in the in game tech tree and VAB, as well as the RP-0 tech tree file: https://github.com/KSP-RO/RP-0/blob/master/tree.yml#L2300

However, in game, it actually comes out to 3128 when dry, and 24291 when full of fuel. While these prices seem entirely fair, how does it come to these strange prices, both the dry and wet, when everywhere it is listed as 400?

**Comment by NathanKell** [comment]
The TL2/3 divide is a bit tough. But while Gemini itself did not fly until 1964, the TItan II was flying rather earlier (March 1962). For that reason there's a fairly clear divide between a system introduced in 1962 (even if it was not man-rated until 1964/5) and a system introduced in 1964/65 which represented a large improvement (120in segmented solids) over the prior 1961-era Minuteman sort of thing.
That's the reasoning behind the Titan II engines being in TL2 rocketry (along with other parts from 1959/60 onwards like the Atlas E engines, or Molniya variant R-7 kit) and the Titan II stuff being in the 1964/5-1968 bracket.

I agree with moving the Nova bits to TL4 construction. I'll have to look back to see what I was thinking with the 10m parts.

My guess for what's going on with the FASAApalloLFTJ25XPlate is that it's getting a large cost increase from its RealFuels hydrogen tank. I'll check it out.

**Comment by NathanKell** [comment]
Ah, extra bit. The thing about the engine placement is that it's a synthesis of pure date, and generation. This is why the Black Arrow engines are fairly low in the tree despite being 1970 vintage, because they're slight rebuilds of late 50s HTP engines. Titan III and Saturn V are very definitely third-generation US LVs (Vangaurd and Redstone being zeroeth, Atlas / Titan I / Thor-Able being first, Atlas E/F / Titan II / Thorad / Saturn I first stage being second, and Atlas-Centaur and Saturn C-1 straddling between second and third).

**Comment by stratochief66** [comment]
Does RealFuels place a specific premium for liquid hydrogen tanks? I will have to check that out. If so hopefully there is a nice way to warn users that a part intended to hold LH2 will cost more than the 'sticker price', possibly a tag that can be added, or something that detects if a part contains < 100L LH2 tankage?

**Comment by NathanKell** [comment]
It does yes. But instead we should set the stick price appropriately and turn off RF's additional costing...

**Comment by stratochief66** [comment]
I will have to check out the actual carrying capacity of the FASA Titan 3A. I readily agree that the Titan 3C is third generation, and the UA 1205 is already placed appropriately to provide that limitation.

According to bnumz, the Titan 3A has a lower LEO capacity than the Titan II GLV (3.5T vs 3.8T)

According to Gunters, the first Thorad flight was in 1966, while the first Titan III was in 1964.

http://space.skyrocket.de/doc_lau_fam/thor.htm
http://space.skyrocket.de/doc_lau_fam/titan.htm

**Comment by stratochief66** [comment]
Note to self: check the in game price(s) of the S-IVb, since it reports a higher price in the tech tree, make sure it isn't seeing a further price increase due to the Realfuel LH2 tankage.

**Comment by NathanKell** [comment]
II GLV had a stretched upper, IIRC, whereas |||A had Transtage which was I think worse than two-stage for LEO, and certainly worse than Agena, and that's why they flew IIIB instead. (Transtage was...really a poor stage.) It was pretty much IIIC without the UA1205s, and was mostly for testing Transtage IIRC.

**Comment by stratochief66** [comment]
According to Bnumz (I also want to compare the Titan IIIA and IIIB in game) the IIIA w/trans-stage had a higher mass to LEO, but a small difference from the IIIB (3.5T vs 3.3T) that probably didn't justify refining the trans-stage to the level of maturity that the Agena had.at that point.

Given the data and dates, I would say again that it appears justified to give people Titan IIIA performance & the trans-stage in the same node as the Titan II GLV.

**Comment by NathanKell** [comment]
Oh, oops, also I evidently got confused between Thorad and TAThor. I meant the latter, which first flew in 1963.

As to the Titan IIIA, I again refer to the 1959-1963 period as more the TL2 period _in terms of LVs_ (TL2 capsules or other things might run later). I also really want to avoid having three different models of LR87/91 in the same node. I think it fair to say that the -5 model is very definitely TL2 (first flight 1962, etc). The -7 is a manrated -5; while it took years to manrate, it didn't actually offer different performance. The -9 was however a change: a switch in nozzle area ratio and other efficiency gains, and rather higher Isp--that is to say, a -5 with the same AR nozzle would not have the same performance.
As to the Transtage itself, I am not that familiar with its development history, but IIRC the engines at least were somewhat intertwined with that of the AJ10-137 / SPS. It was definitely Aerojet's first switchover to NTO and Aerozine rather than Nitric Acid and UDMH, and its Isp is quite close to SPS (311 vs 315).

If there were a TL2.5 I think we wouldn't be having this discussion, Titan III (well, A/B/C) would clearly fit there. :)

**Comment by stratochief66** [comment]
Yeah, I find of figured you mis-stated. Makes sense.

This thread might serve as ammo/pre-planning for the creation of a TL2.5 node? Is there any other engines that would nicely fit there?

Otherwise, I will close the thread when I've move the Nova tanks, unless you want me to leave it open with reminders for you? (7/10m proc parts, moving hydrogen tank prices to the proper part price from RealFuels)

**Comment by NathanKell** [comment]
Yep, definitely leave it open for those.

For other 2.5 stuff..hmm. There's 1.5 stuff I know of (say, LR89-NA-5, or Ablestar variants)...not sure of anything else 2.5ish for the US (by then most Russian engines were staged, so different node anyway).

**Comment by NathanKell** [comment]
Yep, I see the issue. We need to add baseCost = -1 as well as baseMass = -1 for the stages where we don't want RF adding further tank cost.

**Comment by NathanKell** [comment]
On the sizing: I see what the I was thinking, I think. The idea was that there was definitely a step up from 2.5-3m tanks, to S-IV and Proton size, then to S-IVB size, and finally to S-I/II size. However, that leaves N1 out in the cold, and besides that may be a few too many steps anyway even if we make a TL2.75 and 3.25 instead of a single TL3 node.
So yeah, I'm going to change to 3/4.6/7/10/15/50 instead of 3/4/5/7/10/50
