### ISSUE TITLE
Lunar Manned - First

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RP-0#418]
Currently, the first manned lunar mission specifics a biome. I propose that instead either the lunar first is non-biome specific (since landing something manned on the surface successfully is hard enough the first time) or that it be weighted by the proportion of those biomes on the surface (ie. much more likely to ask you to land in a lunar sea or lowlands)

**Comment by ctiberious** [comment]
When I setup the manned lunar landing mission, I didn't include a separate "land anywhere the first time" contract because you've basically already had those in the unmanned contracts.  Plus, we didn't actually do that IRL.  Apollo 11/Eagle had a specific landing site they were aiming for.  If memory serves, they managed to land within several kilometers of that target site.
Admittedly, you do need to have some idea where the biomes are.  Without mods, that can be accomplished with a bunch of unmanned landings (weren't there at least a dozen before Eagle?).

**Comment by stratochief66** [comment]
The Americans made 7 attempts, and remarkably 5 succeeded.
https://en.wikipedia.org/wiki/Moon_landing#U.S._unmanned_soft_landings_.281966.E2.80.931968.29

The Soviets had 7 successes out of 16 attempts.

I also feel that a manned lunar return mission is a hell of a lot different than an unmanned landing with no return.

Even with a number of early landings the KSP planning tools unfortunately make it quite difficult to target a specific biome for your first manned mission, in my opinion.

@NathanKell , opinion?

**Comment by NathanKell** [comment]
I would suggest doing the same as for the LEO missions: the milestone does not have requirements other than "do the thing" but the repeatables have requirements (orbital parameters and duration for LEO, location for lunar).

**Comment by ctiberious** [comment]
I'm wondering if there is a way to use the new extended contract system?  I know that as of 1.0.5 you can have contracts to alter the orbits of satellites that are already in orbit.  I'm not exactly sure how that system works, but could we do something similar here?  Have the Moon Landing mission locate a landed unmanned probe and have the manned contract use that as the target biome?  At least for the first landing?

**Comment by NathanKell** [comment]
You can certainly do that in Contract Configurator, which we use for all these contracts. (That has nothing to do with the stock contract system).
