### ISSUE TITLE
Question about depedencies: SXT and VSR

### ISSUE THREAD

**Issue by Zarbizaure** [KSP-RO/RP-0#469]
So, both SXT and VSR are great looking mods, and we're all doing a lot of work to integrate them the best we can into RO/RP0. However, they were never intended to work with RO. Engines still have attachments rings, and it brings tons of useless fuel tanks that we need to prune! So why are they set as dependencies? Will RP0 stop working if we remove SXT/VSR?

They are some others mods that are intended to look realistic and still cool, and I would agree to set them as dependencies (SSTU, still in dev - Shadowmage is very actively working on its integration, or Kerbalized Rocket engine, also in dev).

So, I truly love the work that is put into RP0/RO by the community, but I think there is problem behind how dependencies work. Or maybe there's a better and logical explanation.

**Comment by NathanKell** [comment]
RSS/RO pushes KSP's RAM limitations rather badly. SXT is great because it doesn't impose heavily on RAM--it reuses stock KSP textures. When @pjf and I were first creating RP-0, we wanted to require only one part pack--RP-0 should be perfectly playable with only its required mods. SXT fits that bill perfectly for those reasons, and also because @Signatum (Lack) has been super-awesome about making stuff at our request. For example, the AJ10 and the X-405 were built by him for RP-0's launch, to replace stock part clones.

Ven's Stock Revamp is also fairly easy on RAM if one prunes the unused old-Squad textures, and it makes the stock assets actually look real (rather than cartoony/bad/both). For that reason, and because it adds some very useful missing parts from the stock lineup (an early engine, a smaller sep motor, etc) RO recommends it.

Further, for those people who (shocker, I know, but it's true for some) don't play with proc parts, the tanks aren't at all useless.

As to the engines having attachment rings--yep. Still better than stock and 99% of other mods though. :)

I'd also like to point you towards exactly what engines Shadowmage and KK (in Kerbalized Rocket Engines) are making: the same modern engines we already have many models of. That won't help RP-0 in the slightest.

**Comment by NathanKell** [comment]
For the record, I think we can reevaluate some of this when 1.1 comes out, if it gives us stable 64bit on all platforms. At that point, we can be much less stingy with requirements, and pick and choose more.

**Comment by winged7** [comment]
I think that FASA and Soviet engines should be added as a requirments (or highly reccomended mods) after 1.1 release - they're not only looking good but also they help filiing the empty nodes more than any other mod..

**Comment by Zarbizaure** [comment]
Ok, so waiting for 1.0 :)
Good point about SXT and VSR textures.
However, I think SSTU provide the best of both world: Engine looks cool, realistic and stock at the same time, they don't have attachment ring and tankbutts are automaticaly generated. Of course developpment is clearly not ended, but it also help in low part count, which reduce ram usage. Though yet (on my install) SSTU is still crashy because of the other parts mod I cannot uninstall.

As @winged7 said: FASA and RN stuff is also cool, but it kills the stock appearance. In the future, it would be cool to let the player choose betwe a stock-alike experience (stock + SSTU) or a realistic one (FASA + RN).

**Comment by SirKeplan** [comment]
SSTU isn't particularly stock like, the engines are relatively realistic in appearance. 
Also I think winged7 meant Bobcats soviet engines not RN, Soviet engines is a great mod for engines, but again is very realistic rather than stock-alike.

If you want Stock-alike then packs like AIES is what you want i suppose.

**Comment by stratochief66** [comment]
Yeah, I don't see how anything about SSTU is stockalike at all. Tantares is a good balance of of stock-alike, in my opinion.

Really, any kludged together mix of clashing styles looks pretty 'stock' to me. Orange tanks, grey tanks, the NASA-like ARM parts.

**Comment by pap1723** [comment]
Is SXT and Ven's still necessary? What do they add that is not added by other mods?

**Comment by NathanKell** [comment]
Off the top of my head, SXT gives us the following early parts:
X405
AJ10-37 (and other Able/Delta engines)
Sputnik and its antennae
Early plane parts (most all of them, in fact)
Gamma 2 and 8 (1970s British engines with 1950s tech level, placed early in tree)
Waxwing SRM

Ven's turns the engines into reasonable-looking things, in particular, and our engine configs are assigned to parts based on their Ven's look. Ditto for Mk1 parts.

That's all I recall offhand.

**Comment by pap1723** [comment]
Closing this as it has been discussed ad nauseum and we always arrive back at the same place.
