### ISSUE TITLE
Engine prices need fixing

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RP-0#490]
Reason 1) gutsy-feely. Soviet launchers are so much cheaper than US hardware, this just can't be right.

Reason 2) Gameplay: Things just don't work out. The RL-10 only becomes worthwhile at payloads in excess of 5t to the Moon / Mars; the Saturn5 is by no means big enough to justify J-2s on the second stage; and SRMs are like 10x as expensive as similar performance from liquid-fueled boosters. I guess there's good reasons why real-life rockets tend towards solids at lauch and hydrolox as early as possible, but Realism Overhaul doesn't reflect this.

Reason 3) sources. Knowing full well that the above two wouldn't convince anybody, I tried to find actual prices. http://www.coldwarweaponsystemcosts.com/resources/EnginesPDF6.pdf gives a few tidbits like
- E44 -- "NASA has ordered 30 F-1 rocket engines and varied support services from Rocketdyne at a cost of $141 million.  Source – Technology Week, November 28, 1966, p 14."  -- $4.7m per engine
- E19 -- "NASA has increased the value of North American Aviation, Inc., Rocketdyne Div., contract for the J-2 engine by $75.8 million for a new total of $206 million.
  The add-on provides for 48 more engines to be produced, raising the total purchase to 103 engines.Source – Missiles & Rockets, December 6, 1965, p 13. " --  $2m (all 103 engines) / $1.6m (last 48) / $2.36m (first 55)
- E56 -- "$19.7 million for manufacture of 114 [H-1] engines. Source – Aviation Week, November 25, 1963, p 30" -- $173k apiece
## 

Also of interest, http://www.coldwarweaponsystemcosts.com/resources/LaunchvehiclesPDF5.pdf
I especially like item  LV10: "$13m based on limited production of 8 flight vehicles [...] $9 million could be achieved with a production rate of 25 boosters per year for 5 years."

This, together with the give-or-take $800k for J-2s, suggests that we should treat any numbers as no more than a ballpark figure.
## 

coldwarweaponsystemcosts.com is a ternary source, but the best I could find; I've been browsing NASA press releases from 1965/66 and came up empty (at least when it comes to engines: there's a lot of construction and wiring contracts in the press releases). It's a shame, I'm pretty sure these things are public -- possibly not only the press releases but the actual contracts.
## 

From what I did find, I suspect that soviet engines are priced well, while US hardware is too expensive, especially Hydrolox and Apollo parts. But then again, the same source mentions ~$9m for a Titan II (twice that when man-rated); my in-game vessel costs 4500 funds, which suggests that our launchers may be too cheap overall. So while soviet engines may be more realistically priced than their US counterparts, maybe it would be wiser to raise the soviet prices after all, just to bring in-game launch costs better in line with real-life figures.

Talking about launch cost: From what I gather, IRL liquid stages are cheaper than solids at the factory door, but appreciate considerably by the time they leave the pad. Right now, the big UA-120x SRMs cost on the order of 6000 funds apiece and don't compare favorably even to a LR87 booster, much less to one driven by RD-275s.

Therefore I suggest making tanks a lot more expensive than they currently are. Right now, the Titan 1st stage tank costs approx. 400 funds and jumps to 1600 if I switch it to hydrolox; something like 2500-3000 for the vanilla tank would possibly make more sense. I'm not sure if hydrogen tanks really need to be more costly: we buy tanks by volume, and the low density alone makes for bigger and hence more expensive tanks. The current 4x factor is certainly way over the top.

**Comment by NathanKell** [comment]
**Schnobs** adds:


I think it would be more important to get the big picture right: since the mid-to-late sixties, the basic recipe is to use solids at launch time and then hydrolox as a second stage, if not as sustainer from the ground up. The game should replicate this.

I'd leave most prices about where they are, but would make the hydrolox stuff a lot cheaper (not, or not much, more expensive than more conventional boosters). I'd cut back heavily on the alternate configuration costs, though, which often add like 50% to the baseline, in some cases more than doubling it. Actually, I think that more often than not the prices should go down with refinement. (1)

Thus most engines would probably be a lot more expensive than they really were. Then again: $173k for a H-1 (see above), with turbomachinery and everything? If we take that figure and run with it, the small pressure-fed AJ-10s will have to cost 50 funds at most, and tiny parts like RCS go into the fraction-of-a-fund realm.

I'd like to put a premium on sheer scale. This would mostly affect the F-1 and M-1 engines.

Even with overpriced engines, the solid<->liquid calculation doesn't work out. Flight test could eventually add a new side to this, with SRBs being more reliable than clusters or even single huge engines. But for now, this will have to happen through pricing, and I don't think it should be engine prices alone. Tanks will have to become more expensive.

Wouldn't it be nice, part 1: tanks are costed by volume. It would be more reasonable if the price scaled by surface area instead (2), with girth being more expensive than height; maybe progressively so. Bonus points if the progression could scale with techlevel, so that what's outrageously expensive at first becomes quite affordable later on. (3)

Wouldn't it be nice, part 2: I'd like to keep a semblance of relative cost, that is, if one design was notoriously more expensive than others, our prices should reflect this. Given how little data I have, this is totally out of the question, though.

(1) Lots of caveats, of course, but that's the general idea.
(2) not perfect, but a great improvement over pricing by volume.
(3) Stages to Saturn outlines some problems with assembling "large diameter" 33ft tanks; a 1990s study about an Ultra Large Launch Vehicle points out that 120ft tanks for LNG ships were then in serial production.

**Comment by NathanKell** [comment]
@stratochief66  Yes, I do want to change the pricing structure, since KCT now allows us to separate part costs from launch costs. That would leave us with:
entryCost: the cost for R&D on the item, as well as setting up the manufacturing line
cost: the cost per item

Then launch cost, based on the difficulty of integration etc.

With that done I could well see H-1 costs down to ~200 funds per, and certainly F-1s at 4700 per.

The other aspect to this is that launch costs should inflate over time, since the price of human-hours goes up. Later hardware might well be cheaper to manufacture, but it's the human labor putting everything together that is currently driving costs, AIUI.

**Comment by stratochief66** [comment]
Cool! I'm glad I didn't remember your idea 100% wrong.

An idea that came into my head regarding hydrogen. We could have a class of
hazardous fuels that are fairly expensive to use (like LH2 is how) but that
get cheaper, either with time passed since you unlocked or started to use
LH2 in your craft, or cheaper as a function of the amount of LH2 you have
built into craft you have launched. This concept could apply to other
hazardous fuels that didn't see use in history due their hazard and
handling costs/risks.

**Comment by NathanKell** [comment]
Interesting. It does make sense that it would get somewhat cheaper over time. Although I think @Schnobs may be underestimating the cost of handling hydrogen somewhat--it's more that it is cheaper in human-hours to have a much more capable (i.e. hydrolox upper and maybe core) LV even if that LV is more expensive in terms of equipment. See SpaceX, which is very definitely not using hydrolox. And their throw weight to GTO is only now beginning to match Atlas V's low end despite an LV double the mass of Atlas V (let alone Delta IV).

**Comment by Schnobs** [comment]
There might also be the issue of scale. The first stage has to structurally support anything on top of it, at several g's. As you scale up your LVs, you should eventually run into diminishing returns.

**Comment by Temeter** [comment]
Idea: Wouldn't it make sense to dynamically lower an engines cost every time you launch it? That would already go a step towards simulating mass production, and how proficient you become in handling certain equipment.

Ofc course it needs to be capped somewhere.

**Comment by stratochief66** [comment]
@Temeter that would be a phenomenal mod, if that could be implemented.

I can't believe I didn't weigh-in in favor of that concept earlier. Perhaps some basic economics/research could provide a default function to use for the decreasing cost of an engine as more of them are built? Again, I think that would have to be its own mod, because implementing that seems tricky. Part price couldn't just be looked up from the parts.cfg produced by RP-0 as it is now.

@jwvanderbeck did a phenomenal job with the functions behind TestFlight, perhaps he wants to weigh in?

**Comment by NathanKell** [comment]
We're finally implementing launch costs. Bumping.

**Comment by NathanKell** [comment]
Changes implemented. We're still going through more than the early engines tho.
