### ISSUE TITLE
Community Science Logs updates

### ISSUE THREAD

**Issue by Veskenapper** [KSP-RO/RP-0#515]
For those of us who can't code and shouldn't model, the Community Science Logs seem a great way to help out a little. But which ones need updating still?

It would also be nice to have some way to access the full base of science logs that are in so far, just to see more examples.

**Comment by batuhantasli** [comment]
I don't know if it's up to date, but it should be useful
https://docs.google.com/spreadsheets/d/1WeuKC0aJGLwB4iJv85BmBbaVBASX56tYLaRNcKTx3z0/edit#gid=1631774271

**Comment by NathanKell** [comment]
@batuhantasli yes, just so! It is probably not up to date with the basic experiment information that was added thus far; the most up to date listing of science reports is here: https://github.com/KSP-RO/RP-0/tree/master/GameData/RP-0/Science/Results
As can be seen by their lack, we have no Geiger-Mueller tube results, and no Orbital Perturbation results. So that would be the first area to focus on (perhaps looking at what's in the spreedsheet for inspiration or, if good enough, direct porting), and also it looks like various other bodies need to be filled in even for what already exists in that folder.

**Comment by Veskenapper** [comment]
@NathanKell @batuhantasli Nice, thank you both!

I'll go ahead and edit the Results .cfg's in a fork of my own, using the data from all available sources; that way it should be even easier to take a look at what else is missing.

**Comment by pap1723** [comment]
Merged for a while
