### ISSUE TITLE
SSTU engine cluster pricing is broken

### ISSUE THREAD

**Issue by Temeter** [KSP-RO/RP-0#538]
While the weight multiplicator is fixed, the pricing for increased engine counts is still broken.

For example:
- AJ10early/mid price is static.
- H-1/RS-27 price proportionally rises with every new engine.
- RD-107A price rises about 50% with every new engine. 
- RD-107X still ignores pricing in tech tree (also static cluster pricing).

**Comment by SirKeplan** [comment]
Well, I think I at least know why this is.
It seems to be based on on the cost field in the `CONFIG` nodes, if this field is 0, or not set, then the cost doesn't increase when you make the engine into a cluster.

**Comment by Temeter** [comment]
Sadly I cant do much here, that code is far to complicated for me, but thanks for looking into it! Tell me if there is some simple help/testing I can do.

**Comment by jwvanderbeck** [comment]
@SirKeplan can we recap for my benefit here?  My understanding is that SSTU itself does some adjustment of prices based on cluster size in its own plugin yeah?  So is the problem that we aren't modifying? Or is the problem that SSTU is in fact not doing that?

**Comment by SirKeplan** [comment]
@jwvanderbeck let me try then. So there's `SSTUModularEngineCluster` in the plugin which handles the clusters. Now that plugin does have code for adjusting the cost for clustered engines.
However it turns out that when RealFuels is installed, that code is disabled with a MM patch that sets adjustCost = false

So i am still a little confused as to why the costs are coming out wrong, either there is something else in SSTU that sets the cost(wrongly) based on the `CONFIG`s, or there is some MM cfgs i haven't seen that are responsible.

 https://github.com/shadowmage45/SSTULabs/blob/master/Source/Module/SSTUModularEngineCluster.cs#L457

https://github.com/shadowmage45/SSTULabs/blob/master/GameData/SSTU/Patches/EngineMassHandling.cfg#L9

**Comment by SirKeplan** [comment]
@NathanKell this is a wierd bug, for SSTU engine clusters the price seems to be currently following this: `price = partPrice + configPrice * engineCount^2` (made up variables)
i think it may be a RF bug, but can't find what would be causing it. have you got any idea what would be causing the extra multiplication of engineCount?

I'm thinking it's in RF, because SSTU does not change the cost when RF in installed, apart from setting the ModuleEngineConfigs `scale` to the no of engines in cluster.  https://github.com/shadowmage45/SSTULabs/blob/ac95fa838064f8ad321ec1d47564b3a16c9e728a/Source/Util/SSTUModInterop.cs#L33

**Comment by SirKeplan** [comment]
This fixes it, made a PR for ModularFuelSystem/Realfuels.

also the SSTU part pricing should be re-enabled.

https://github.com/NathanKell/ModularFuelSystem/pull/149

**Comment by Temeter** [comment]
AWESOME <3 <3 <3

I'll take a look at it and report how it works for me!

**Comment by SirKeplan** [comment]
@Temeter  .dll file https://www.dropbox.com/s/pzrbhkd2k7alsg6/RealFuels.dll?dl=0

**Comment by Temeter** [comment]
Man, I just spent literal hours fixing my testing install. Talk about saving time. xD
Not to mention like 3 random crashes between the minute long loading times.

Adding the .dll file just completely breaks RealFuels for me.
Assumption: Are the 'RealFuels.dll.mdb' and 'RealFuels.pdb' files connected to the dll and maybe need to be updated accordingly as well?

**Comment by Temeter** [comment]
My .pdb is 224.768 Bytes.

**Comment by Temeter** [comment]
Basic functionality works, the engine cost multiplies correctly! Even just the gui works correctly. Damn good job.

I'm seeing one issue remaining: The additional cost for more expensive engine variants is only applied once, regardless of engine number. 
E.g. the RD-108 is 700, three are 2100. It's K variants costs 800, but three K's are 2200.

That said, it is functional for normal gameplay, as long as new issues won't show up.

**Comment by jwvanderbeck** [comment]
You should only have the dll. The pdb and mdb files are debugging databases

Get Outlook for iOS




On Wed, Jun 1, 2016 at 9:03 AM -0700, "Temeter" <notifications@github.com> wrote:












Basic functionality works, the engine cost multiplies correctly! Even just the gui works correctly. Damn good job.



I'm seeing one issue remaining: The additional cost for more expensive engine variants is only applied once, regardless of engine number. 

E.g. the RD-108 is 700, three are 2100. It's K variants costs 800, but three K's are 2200.



That said, it is functional for normal gameplay, as long as new issues won't show up.

**Comment by Temeter** [comment]
So they aren't even needed? Huh, guess they got accidently left in the official download.

**Comment by SirKeplan** [comment]
this is weird. it works fine for me, three K variants are 2400. what version of SSTU are you using?

**Comment by Temeter** [comment]
0.4.31.115, should be the most recent.

**Comment by jobadiah08** [comment]
I am seeing this bug. Using RF v12.0.1. A cluster of 8 SSTU H-1B engines costs ~$70,000.
Appears to be using: Cost = (BasePrice+UpgradeCost) x EngineCount
where UpgradeCost is equal to the cost to upgrade all the engines in the cluster. So if an engine costs $1000, $1000 to upgrade, and you have 5 engines
Cost = (1000 + 5000) x 5 = $30000
It should be: Cost = 1000 x 5 +5000 = 10000 (BasePrice x EngineCount + Upgrade Cost)

Playing on 1.2.2 with RO/RP-0

**Comment by pap1723** [comment]
SSTU is not supported past 1.3.1
