### ISSUE TITLE
Hiding/tagging unsupported parts

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#57]
When parts don't say "non-RO", people tend to think that means RP-0 supports them. We should at the very least tag unsupported parts, IMO, and consider hiding them.

**Comment by OtherBarry** [comment]
I'm unsure how i feel about this. On the one hand, RP-0 is a very custom career ode with a very clear intention, hence, hiding unsupported parts prevents people from ruining RP-0, without losing the ability to play sandbox with whatever parts they want.

On the other hand, you have pjf's view, which is that RP-0 is very light weight, and as compatible and supportive of whatever users choose to do with it as possible, so hiding things is a bad idea. Tagging them may not be great either, as when I play, using a "non-RO" part makes me feel guilty, as if i've broken the rules of the realism mods. Which again, doesn't really fit with the (not that i like to call it this, but it is apt) pjf RP-0 way.

**Comment by NathanKell** [comment]
The problem is RL10 available from node 1 for like 600 funds...

Sent by my thumbs, slowly.

**Comment by OtherBarry** [comment]
Which RL10? From which part pack?

**Comment by NathanKell** [comment]
KW, IIRC. Also it appears BobCat's engines unlock early too.

You're correct that hiding is bad for sandbox. Instead, we can just chuck them in the ORPHANS node, it's what it's there for. Since the problem seems worst for engines, we might only do it for engines, so that other parts we don't touch don't necessarily get made unavailable in career.

**Comment by BevoLJ** [comment]
Would this affect the non-ro parts we've added.  I add Kos and IR.  I know they aren't supported, but feel they greatly enhance my style of play and like where they fall in the tech tree right out of the box so use them anyway.

**Comment by NathanKell** [comment]
Create a mini-PR? :)

**Comment by Felger** [comment]
Suggestion:
Create a RO Filter config for Filter Extensions ([Forum Link](http://forum.kerbalspaceprogram.com/threads/104231), [Github Link](https://github.com/Crzyrndm/FilterExtension/))

**Comment by bax-** [comment]
Both of Felgers suggestions sound great to me (who is otherwise totally not involved in this).

**Comment by cherrydev** [comment]
The benefit of the autopruner is it would create significant memory savings, but would obviously need to be manually run by the player.  I think it would be reasonable to prompt the user the first time they start the game with RP-0 and indicate to them that this is an option, and otherwise toss them into the Orphans CTT node.  Another alternative would be to include a shortened link in the "part not supported by RO" blurb that would explain what this message means and how they can get rid of it (by running a pruning link).
There's no way to get ModuleManager to actually not load a part at all, is there?  Or otherwise avoid loading a part's textures into memory?

**Comment by NathanKell** [comment]
Half done: 78e9514e5158e8f2e1b8b3fd464d2e4ffb45592c
I still need to make it report when an item is placed but not priced.

Of course MM can make KSP not create parts. It's just all assets are loaded whether or not they will *ever* be used by the game.

**Comment by NathanKell** [comment]
And yes, talking up pruning is a good idea. :)

**Comment by NathanKell** [comment]
This is done, although the pruner interaction still ought be handled. Nonetheless I am closing this; reopen if desired.

**Comment by pjf** [comment]
> Reopen if desired.

It is I! Re-opener of threads!

One of the reasons for using the CTT is that it means a whole bunch of parts from third party mods will already be correctly placed, especially on the right-hand-side of the tech tree. All my mods which let me mine fossilised unicorn poop or build dirigibles from Martian Liftwood are already in the right nodes.

Unfortunately, they have big awful "part not supported by RP-0" messages on them. This breaks immersion, and to remove this means a whole bunch of work placing parts which *are already in the right spot*.

Of course, it *is* nice to know when a part is somewhere because that's where RP-0 placed it, so I'm going to propose we keep the filters, but we tone them down. Let's just add a '**' to the part name if it's not placed by RP-0, and a '*' if it's placed but not costed. Those provide visual cues for third party content, but don't detract from the RP-0 experience.

~ Paul

**Comment by jwvanderbeck** [comment]
The problem, if you want to call it that, with the subtlety is that amazingly even with the big annoying immersion breaking text players *still* are shocked when we tell them a given part was not supported.  

Personally I find it hard to imagine that the default location of things for CTT is in the place that we want them, but I don't know enough about CTT to be sure of that.  Given that we are adding entirely new nodes and paths though, it seems unlikely.

Maybe a compromise is to leave the titles alone, or with a small notation as suggested, but still add an much more obvious string to the start of the part description?

**Comment by NathanKell** [comment]
We have, I think, three classes of part.
* The first class of part is the most cuddly: Stuff designed for CTT where we don't need to move the node, we just have to give a reasonable price (because a stock-KSP-balanced price will not be reasonable, let alone correct).
* The second class of part are those that are not CTT-compatible, or even techtree-compatible at all. For example, BobCat's engines are placed in the Start node by default. These are obviously wrong, although never underestimate the combination of avarice-tinged obliviousness that would make one think, despite it saying it's not supported by RP-0, that a 2000s-era super-efficient super-powerful engine really should be available in 1951 for five thousand pucks.
* The third class of part is the most troublesome: those parts that are placed *somewhat* correctly. Examples here would be, say, rocket engines which at least will be placed in *a* rocket engine node, just not the right one. However, without an obvious warning from us, a player who does not know about rocket history might well think that a NK-33 really should go in the second rocketry node rather than the sixth.

However, that said it's important to remember that even in the cuddliest of cases, we *have* been doing various things to the CTT, including converting construction nodes to hydrolox nodes; right now all of Infernal Robotics is part of Advanced Hydrolox Engines. We doubtless will have to do some similar splicing in the future re: CTT, so even the best case is not safe.

**Comment by pjf** [comment]
### Re-purposed nodes

I'm not a huge fan of changing the CTT, because it *does* result in misplaced parts. I'm more in favour of adding new nodes than changing existing ones, but I think that's a separate issue for a separate ticket.

However since we've already done this, I suggest that if we *have* re-purposed a node for a completely different use, we have MM code which sweeps the existing parts to a new node (*not* orphans) which makes sense for them to go in. That means third-party mods still end up with parts in sensible spots, avoiding the big immersion breakers of "why is X in the hydrolox node?".

### Non-techtree parts

BobCat's engines and friends are going to be a problem no matter how we do things. They're not designed for *any* career mode. Obviously we should place and price these as appropriate, especially if we have contributors helping us with that.

### Part titles

> Maybe a compromise is to leave the titles alone, or with a small notation as suggested, but still add an much more obvious string to the start of the part description?

Having a distinctive title is nice because they're easily visible, which is valuable for RP-0 developers. That's which is why I'm suggesting 'Laser Enfrobnicator**' as a title, which still tells us that it's not placed by RP-0, but isn't as eye-watering as 'Laser Enfrobnicator (non RP-0)'.

Having a full description at the bottom of the part description seems fine to me. It's a big wall of text, so it's not breaking immersion very much by having a node at the end of it. If that's `** Part not supported by RP-0`, then it also makes it clear what the '**' in the title means, too.

**Comment by NathanKell** [comment]
@pjf, the parts are misplaced anyway. RO does interesting things to engines, human spaceflight is hard, wings really aren't that hard (nor are girders), the list goes on. Yes, for the specialized mods that specialized nodes in CTT were built for, *they* will be placed correctly. But for *general* hardware, hardware that doesn't have whole sets of nodes built for it but rather is placed mostly within the stock tree, they will be misplaced anyway.

I agree about doing a BEFORE[RP-0] pass that blanket-moves old-construction stuff to some other node(s) though, that's a very good point.

Regarding part descriptions, I have watched far too many youtube videos and fielded too many forum questions to be under the misapprehension that anything but an obvious tag will work (indeed, such a tag was requested multiple times), and I care much more about the *gameplay* being immersive (and nothing ruins gameplay immersion more than a misplaced or mis-priced part that makes the game ridiculously easy and makes hard-earned resources not actually matter) than the UI.

The obvious solution here is to place and price as much as we can, of course, which is what you're doing (and what I will try to do when I and GF un-sick).

To expand on the middle point: you are well known to favor gameplay over historicism, and while I have my differences on that point I do respect that approach, for if a game (or mod) is not fun there isn't much point. But I think, for all the way the "non-RP0" tags shout WIP, they do much more for gameplay--for *fun* --than they subtract from polish.

**Comment by pjf** [comment]
@NathanKell : I'd quibble that the CTT is mostly specialised nodes. Nuclear engines, off-world colonisation, science outposts, plasma propulsion, antimatter containment, microwave power, all those wonderful things. Early (pre-2030) engines will be misplaced, as will wings, girders, structural doo-dads, and other such stuff. From that perspective, all the early things which RP-0 has thus focused on will be misplaced.

Having said that, I concur. Misplaced or mis-priced parts do break immersion. That sucks. And if we've players who are requesting this and it's coming up regularly, then I'm happy to support the current tags being in place. (And hence I'm re-closing this ticket.)

I'll open a separate ticket for discussing the best way to place/price parts. I have some ideas which might expedite the process.

Many thanks!

~ Paul
