### ISSUE TITLE
Procedural Avionics Cost

### ISSUE THREAD

**Issue by BevoLJ** [KSP-RO/RP-0#631]
This doesn't seem to be working as intended in my save.

> costPerControlledTon = 4425
https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/ProceduralAvionics.cfg#L171

In practice the current costPerControlledTon of 4425 seems to = 17,588 funds

A one ton probe should be expensive, but that seems a bit high.  It also makes a .2t probe = 3517 funds.
The cost of the upperStage & booster seems to be getting scaled up similarly but due to their low cost, it isn't as prohibitive.

Could I be doing something wrong?

**Comment by rsparkyc** [comment]
Did you check out the spreadsheet for this?
https://docs.google.com/spreadsheets/d/1lpuszH_nUbWlTXZzfOMzsy-uhUNh016eNu0WL8x6qvU/edit#gid=1101913381

This tech level is on line 14.  It's based around a unit designed to control .3T, and costing 1358.9.  I would think a .2t probe would be even less than that, but I think it could be more if you tried to reduce the size of the avionics unit (smaller, lighter units are more expensive than bigger, heaver units)

Could you try making a proc avi unit of a similar size to a Rander Block I core, and then setting it's controllable mass to .2 or .3t and see what you see?

**Comment by BevoLJ** [comment]
.3t = 5,354 funds
![cost](https://cloud.githubusercontent.com/assets/5301213/24377343/b94adcb0-1304-11e7-9052-f9be30751a01.PNG)


Here is my tech level (Not yet to Ranger III)
![sci](https://cloud.githubusercontent.com/assets/5301213/24377350/bd6b01bc-1304-11e7-9512-7e8f08fcd6f5.PNG)

**Comment by BevoLJ** [comment]
Hmm, shouldn't the dry mass be less than wet mass? (see first image) What is going into that?

**Comment by rsparkyc** [comment]
Yeah, the dry mass vs wet mass thing is weird, but that comes from procedural parts, so I don't know what's up with that.  Your issue is different, let me explain what's going on:
You've made a part whose volume is about 63L, while a Ranger Block I core part has a volume of 125L (cell I:14 in the spreadsheet).  As you reduce the volume of the part, it gets harder and harder (thus more expensive) to fit the same amount of avionics equipment in the same space.  Notice your "Percent Utilization" is up to 100%.  While that's the most efficient weight-wise, it's also very expensive.  Make the part physically larger, but set it to the same tonnage and you should see the costs go down.

**Comment by BevoLJ** [comment]
Ah, that fixes everything!  Makes the cost much better.  Thanks!

Perhaps there is a way to inform users of that?

**Comment by rsparkyc** [comment]
It should all be in the readme: https://github.com/KSP-RO/RP-0#optimal-utilization-percentages

**Comment by rsparkyc** [comment]
Yeah, i was hoping the percent utilization display would help with that, but perhaps I could also display current cost and mass multipliers.
