### ISSUE TITLE
New Tech Tree?

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#655]
Hello Everyone,
I am working on a new tech tree for my RP-0 careers going forward. I am a person that likes to think linearly, so I have designed a tech tree that works that way. Everything is broken up into categories and there isn't really any cross-branching that happens. I understand in the real world, this isn't necessarily how it works as in order to build a better engine, you need to have good enough materials science. However, the way it is organized in the current tree is lacking for me.

I have attached an image of the tree as it currently stands in game. I have balanced the costs of the tech nodes so that up through Tier 10 (Modern Day), all costs are in line with the current RP-0 Tree. There are obviously more nodes than the current tree, and some might possibly not have any parts in it depending on the mods installed. If that is the case, the node is automatically hidden and the tree dynamically adjusts to have the proper prerequisites for opening the next node.

I am going to be placing parts into this tree for myself, but I need to know the following:

1. Is this something that RP-0 would want to adopt as the distributed in-mod tech tree?
2. If the above is no, would we want to even let people know it exists as an alternative?

The answers to the above questions affect how I will proceed. If it is to become the in-mod tech tree, I will immediately place all of the parts that are in the current tree into the correct nodes.

My answer would be to distribute this as the official RP-0 Tech Tree. It is clean, parts can be placed into the proper nodes very easily and it removes having the Community Tech Tree as a dependency.

Let me know what you think and I will modify my approach!

http://i.imgur.com/OXVvzq5.png

**Comment by stratochief66** [comment]
Because it is such a massive change, I'd suggest working it as an alternate tree for now. I think RP-0 can definitely be open to making people aware that alternate RP-0 trees exist, through a mention and link in the RP-0 OP. IMO, doing it through CKAN could be confusing, because then people may not be aware which tree the have, which is an important thing do know for troubleshooting.

I see a lot of serious advantages to doing it that, way, because then you have full autonomy to move around the tree, and interpret, implement or discard all the placement advice you get as you get feedback for this tree. In comparison, if we were considering immediately moving your tree in as the RP-0 tree, every change you suggest would have to be play-tested and compared to how it affects RP-0 play. Once you've completed your tree, it has had a lot of play, feedback, tweaking from people there is a very decent chance we would move it in as a replacement for the current tree, but developing it entirely first (like, as a separate mod, or a separate branch of the RP-0 repo?) gives you a lot more flexibility.

Is the way you would code it entirely different by the two routes? Is there a way we can make that easier for you, so that it will be easier to switch at a later date? For example, making the current RP-0 tree.cfg build with a :NEEDS[!Paptree] or something, so you don't have to code it such that MM runs the regular tree, then your tree?

@NathanKell @jwvanderbeck (and obviously anybody else, I'm just poking a few for specific feedback) please weigh in if you think my comment/suggests are off base.

**Comment by jbengtson** [comment]
I agree with @stratochief66 on the alternate tree part, that would definitely give you more freedom to develop it. I would playtest it as well.

At a glance it makes a lot of sense, very structured, and I hope it represents the future of RP-0. As a suggestion I would move Material Sciences up next to Fuel Tanks (or move Flight Control up under Flight & Planes) as I suspect they are somewhat intertwined and can use requirements from the other.

**Comment by pjf** [comment]
+1 for having an alternate tree.

I'd suggest making the current RP-0 tree.cfg with a `:NEEDS[!RP-0-Tree]` or similar, rather than checking for a specific tree. This would mean:

- Users can drop the new tree in and the built-in tree would gracefully disable itself, which makes installation simple through both CKAN and manual means.
- It allows for anyone to develop their own RP-0 trees without us having to grow the `:NEEDS` decorations for each one.

**Comment by pap1723** [comment]
@pjf Tagging the existing tree with a `:NEEDS[!RP-0-Tree}`will not accomplish the goal I don't believe. Well, it will to a point, but the player will also have to understand that Community Tech Tree cannot be installed, or there will be conflicts between the two of them.

**Comment by NathanKell** [comment]
tbh we should have broken our dependence on CTT a long time ago, we were just waiting for someone to have time to make a tree from scratch rather than MMing. (Someone, I forget whom, volunteered, but then nothing happened.)

**Comment by PhineasFreak** [comment]
@Niemand303 had opened a discussion a while back for overhauling the tech tree. On a followup issue, @Schnobs started working on porting the tree to work without CTT (i also offered a tech tree sample) but no progress was done.

The worse thing about tech trees is the icon placement. Even with the external program [TED](http://forum.kerbalspaceprogram.com/index.php?/topic/89213-win-ted-ksp-tech-tree-editor-v024-alpha-early-testing/) you have to spend a lot of time actually placing the icons (and writting the necessary "code" to link them). Also, do we want to port the tree "as-is" or make changes as we go?

**Comment by Theysen** [comment]
After some early career playtesting with the "recommended" settings preset on hard I encountered following issues, especially for the get going process.

Way too many nodes early on with way too high science costs, you can't crave that many science from the little experiments we have available. 

People wanting to use a Juno fuel tank by FASA need to spend 29 science for example just to get that tank early on, no chance to crave that much out of sounding rockets unfortunately.

Either costs need to be reduced or the hard preset shouldn't be the inofficial preset used to play. 

The 'old' tech tree made the science points well spent imho, enabling differing playstyle by just unlocking a few nodes in the beginning, this here is very limiting if you're following a certain playstyle at the moment. 

I'll have to restart a new save on "normal" maybe to make more comments about the tech tree progression and how it plays out.

**Comment by eberkain** [comment]
I like the tech tree layout, I wonder if it would be possible to make it so a tier had to be completed before any tech in the next tier is taken?

**Comment by pap1723** [comment]
Closed moving to a new clean issue to start over.
