### ISSUE TITLE
Procedural avionics units can survive reentry

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#691]

**Comment by PhineasFreak** [comment]
Since the proceduralAvionics part config inherits it's thermal parameters directly from the "stock" Procedural Parts proceduralBattery config, it has a *maxTemp* field of 2000 K.

Patching this via RO would be the best option, since both the battery (FOR[RealismOverhaul]) and the avionics core (FOR[RP-0]) can be patched at the same time.

**Comment by rsparkyc** [comment]
For now, I lowered it even more.  Looking at my config cache, it was showing 2000 as the max temp.  I lowered this to even less than than, and added a skin temp as well.
