### ISSUE TITLE
Adjusting RP0 costs to reflect integration prices, and overall KCT formula tweaks [discussion]

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-0#719]
I'm going to use this as a scratchpad to reflect my current thinking of this and for discussion.

I thought about this for a while.  The original plan was using the rollout costs to reflect the higher integration cost of liquid fueled engines or human habitable components, and also to add a price to reusing a craft.  I was looking at using a rollout cost multiplayer of 5x or so on LFE's, for instance.

However, after giving it some thought, I see a couple of problems.
1. Even if Magico adds UI to the overall rollout cost, players won't understand why the rollout costs are several times the cost of the rocket itself, nor understand the various multipliers on their parts because they'll be hidden behind one large price in funds.
2. Nathan said our VAB is not part manufacturing, it's part integration.  Therefore, the VAB costs should reflect integration prices, which they currently do not, they reflect the historical 'price from the manufacturer', I believe
3. Rather than making reuse 'not as good', this would make reuse terrible - most of the cost of the rocket launch would be in rollout.

What I think is a better plan, then, is to reflect integration costs in part costs in the VAB.  I need to check with NK if his preprocessor tags can be read when MM is running so we can dynamically apply our own multiplier then.

I'd still add a rollout cost, to solve the exploit of too-cheap reuse - but I think it should be some fraction < 1 of the VAB integration price, not several times higher.

Other things I'd like to tweak with the current KCT formula -

- Rollout times:
      - Rollout Times and launchpad prep feel too low, relative to integration time, and I think they should reflect more than just the BP cost of the rocket.  
     - I think it would be good to use the launchpad level as a fixed increase to the rollout time - no matter how small your rocket, if you're launching from complex 39 at Kennedy, it's going to take a while, and it would be good to encourage players to maintain multiple pads for various uses.
     -Since LFE's would already cost more, this will be reflected in the rollout time, but may need more scaling.  Possibly there should also be a multiplier to reduce rollout times & costs for jet engines?

- Rollout cost:
    - Rollout cost should reflect overall rocket cost, since now LFE's will have a bigger factor in that.  Possibly there should still be an additional multiplier for LFE's
    - I think a rollout cost component associated with launchpad size is also good - using a big pad for a small rocket should be inefficient.  This would encourage multiple launchpads as well. 
    - I think a rollout cost of 20%-30% is reasonable.

**Comment by NathanKell** [comment]
The real answer here is to charge an extra integration ('build' in KCT terms) price in addition to the part costs. But that will require MOAR changes in KCT. :]

That said, I'm not sure what portion of launch costs are actually integration costs and what portion are rollout/pad setup, and what portion are day-of (range clearance, launch support, etc). My guess is it's not 90% (not even 70-80% as you suggest) the first bit, though.

For now, I highly recommend not artificially inflating part costs, because (a) for manufacturing, I need to still have access to the actual part costs, and (b) because it's a good thing ingame to not hide everything behind a launch cost.

Finally, as to your point 3--YES. There's a reason reuse is often a fool's errand! :P And even with launch costs only ~5x of manufacture costs you're still saving 1/6 the cost each launch with reuse, which adds up. And note that your system would actually break this dynamic, because if the cost is done during integration ("build"), that's the part that's not redone when you KCT-recover a vessel, so that part won't be re-charged.

I do think in the end there probably should be separate explicit integration costs, but I think for now this should work OK. Launch cost for a jet (with no tagged parts, since they're not going to space they don't need human-rating or to be tagged space-habitable, e.g.) should be uber-cheap, so that should solve that. A rocket-powered thing, however, would be rather more, since the engine has to be overhauled.

As to the rest:
* Launchpad level is already taken into account in the rollout time formula, and it makes a rather severe difference.  It's a multiplier however not also a constant, though, a constant factor (scaling linearly with pad level) does sound like a good thing to add.
* We probably need a couple levels of TagLFE, tbh, to reflect easy-to-maintain engines vs hard-to-maintain ones. E.g. the XLR99 took very little maintenance whereas the RS-25 was infamous.
* Agree on rollout cost having the pad as a component, as well as time.

**Comment by ppboyle** [comment]
> That said, I'm not sure what portion of launch costs are actually integration costs and what portion are rollout/pad setup, and what portion are day-of (range clearance, launch support, etc). My guess is it's not 90% (not even 70-80% as you suggest) the first bit, though.

So what do you think the percentages for each should be, for a rocket?  I think you'd be more of an expert here than I am, I'm guessing based off of the 30% SpaceX is supposed to save for retrieving their booster. 

> For now, I highly recommend not artificially inflating part costs, because (a) for manufacturing, I need to still have access to the actual part costs, and (b) because it's a good thing ingame to not hide everything behind a launch cost.

I don't understand this comment - I'm also saying we shouldn't hide things behind the rollout cost.  Also, if you still need to keep the original manufacturing cost, then if we do the cost modification as an MM patch, we should be able to save the manufacturing cost before overwriting the base cost.  I'm not an MM expert however here.

>Finally, as to your point 3--YES. There's a reason reuse is often a fool's errand! :P And even with launch costs only ~5x of manufacture costs you're still saving 1/6 the cost each launch with reuse, which adds up. And note that your system would actually break this dynamic, because if the cost is done during integration ("build"), that's the part that's not redone when you KCT-recover a vessel, so that part won't be re-charged.

Well, with the SS it seems it was a combination of the massive over engineering needed for a recoverable spaceplane as well as the all the conflicting goals it had to endure,  It's working out of SpaceX.  In RP-0,  1/6th of the launch cost is beyond valueless because you'll have to add more than 1/6th of the cost of the rocket, in most cases, to make it recoverable in the first place.   But my main concern is not being clear with people about where the costs are coming from, so they won't SEE that SRB's are actually a good deal, despite the manufacturing cost.

**Comment by NathanKell** [comment]
SpaceX has far lower integration and launch costs than is the norm for most of space history. They're something of an outlier and I don't think we should balance based on them, especially since the meat of the gameplay is between 1955 and 1975 currently. Also they're known for somewhat optimistic projections. :P

 
MM patching doesn't work like that--MM changes what the game loads, it can't tell the game to load additional stuff like you propose. Parts have a cost. So whatever cost the confignode finally reports, that's the cost the game will load.

However, the simple solution here is to have KCT display the rollout time and cost alongside the build time (and cost, notionally) in the KCT window in the VAB/SPH. Then everything is exposed properly, and we can keep the regular VAB/SPH cost display (and do stuff based off regular part prices, as we need to).


You'll have to add more than 1/6th of the rocket cost to make it recoverable, but not add 1/6th of what drives launch costs. So it should work out OK IMO. And as to making things clear, yes, that's why the KCT window in the editor should display things. :)

**Comment by ppboyle** [comment]
>I don't understand this comment - I'm also saying we shouldn't hide things behind the rollout cost. Also, if you still need to keep the original manufacturing cost, then if we do the cost modification as an MM patch, we should be able to save the manufacturing cost before overwriting the base cost. I'm not an MM expert however here.

>MM patching doesn't work like that--MM changes what the game loads, it can't tell the game to load additional stuff like you propose. Parts have a cost. So whatever cost the confignode finally reports, that's the cost the game will load.

What I'm suggesting is, that, say you need 'manufactured cost' for some future feature.  You'd have a value for manufactured cost, which, since we don't want to update every part right now, in MM, we'd do something like.  I'm guessing you can add the ManufacturedCost field in code pretty easily, right?

ManufacturedCost = cost;
cost = IntegrationCostAdjustment * cost;

Even if you display rollout time and cost in KCT, unless that display breaks down the various parts and multipliers, people will not understand how that cost is generated, though it's true that, at least with it being a running total they can see as they add parts, they can get a better feel for it.

Hrmm - I guess we could also instead just add what the per-part rolloutCost will be as a detail on each part as well though.  So we'd have a field called RollOutCost and have MM write to that...

**Comment by NathanKell** [comment]
Like I said, that's _just not how it works_. Part is a KSP class, and only loads data for fields it has. It doesn't have a ManufacturedCost field, so it won't load data for that. We'd have to go through some weird adding-module hijinks that I'd *really* rather not.

Let's say we have a class foo { double a, b; }
Now we want that class foo to store a third double. **Just how do you pan to have it do that?** :P (When, remember, it's not our class, we only control the text it deserializes from.)

Your concerns apply just as much to, say, engine configs--that added cost isn't displayed anywhere except the engine UI, it's just 'rolled in' to the final price. I don't really see the big deal.

But really, my main point is this: Let's at least try to do some stuff, using the tools we have. :)

**Comment by NathanKell** [comment]
What I'll probably have to do is write a partmodule that exists only to store data (and so it shows up in the part right-click tooltip in the editor). But that'll take a bit of work for sure.

**Comment by ppboyle** [comment]
Gotcha.  I thought if it hadn't taken much to add the ability to put new tags on part, it wouldn't take much to put a new field on one either.  C# reflection magic? :P   Anyway, magico told me why the part cost multipliers weren't working, it was an undocumented variable, I'll try adding that in and testing some values tomorrow.

**Comment by Rounan** [comment]
Well this discussion got highly detailed pretty quickly! :)

I have a couple high-level, totally undetailed comments about RP-0's KCT implementation. Knowing nothing of the "how", here are a couple "what"'s that I think would benefit the next implementation:

**1) More guidance on when & how to buy & spend upgrade points**
When I've gone bankrupt, it's usually been because TestFlight fails a contract for me and I don't have time to build another rocket before the contract expires. After asking for help on #RO, I found the root cause: I was not aware that I should be buying and spending LOTS of additional upgrade points in order to keep VAB and R&D rates in line with the expectations baked into the contract terms.

Is this something that could be addressed through contracts? As in, if it's 1955 and you're still at a total VAB rate of 0.4, you get a contract to upgrade the VAB to some target build rate, with flavor text explaining that you're embarrassingly behind expectations. Contract should have little/no reward, maybe a small reputation bump, just a nudge to let the player know they're failing to do something important. I'm not sure if the contract system has the hooks to handle that kind of KCT integration....

Failing that, maybe an annual pop-up message, "The Year in Review", or some such? It could be written like media coverage of the space race, and detail the progress of "that other space program", but is actually just guidance on where the US (or USSR, or some hypothetical average of the two) was at this time, what it accomplished, and what facilities and VAB/SPH/R&D rates are expected at that point.

**2) More benefit for developing and re-using standard launch vehicles**
First off, this idea feels right to me and I believe it would make gameplay more interesting, but may not actually be a design goal for RP-0. Obligatory salt grain; just my 0.02. Also, by "re-use" I mean "building the same design again", not actually landing and re-flying the same booster. I agree that shouldn't even be possible in the 50s, and certainly not economical until the late game.

Maybe I'm missing something, but I don't see a (significant) difference in cost or build times for the 2nd/3rd/nth construction of a given craft compared to the 1st. The result is that I don't bother saving and re-using launch vehicles as subassemblies, instead just stretching or shrinking the tanks as needed on the same basic engine layout. Effectively, I build a unique LV for each flight, and I don't perceive any penalty for this versus developing a big expensive complicated LV and then launching a dozen or so payloads using it.

I'm not sure how the mechanics and implementation work out; I have no understanding or opinion on whether these savings should be modeled as "production" or "integration" costs. The outcome, however, should be that players clearly see cost and build time coming down on subsequent productions of the exact same sub-assembly. If I could see ~25% savings by the 3rd-5th build of an LV, this would be enough to change my behaviour. I also think it's on the low end of  mass production-type savings on '50s-era rocket tech: [Redstone cost $92M](http://www.astronautix.com/r/redstone.html) to develop, and I'd wager the 1st one off the line cost a whole lot more than the final $2M "flyaway unit cost".

**Comment by NathanKell** [comment]
1. definitely needs to be addressed in tutorials. Not sure how much farther it makes sense to go.
2. We now have tooling support, although not full stage or LV detection support.

In other news: implemented global multipliers in KCT. So we can multiply the whole BP cost by 1.5 when something is human-rated, for example.

**Comment by siimav** [comment]
Should close this old issue now that integration and rollout are shown separately in the KCT UI. If anyone has feedback and ideas for the current system then those should go into a new issue.
There's still a couple of interesting ideas that were mentioned in this discussion that might be worth carrying over to a new issue.
First we might want to add a flat rollout time to every pad size so that launch cadence wouldn't get crazy fast as more and more points are dumped into VAB. Adding a refurbishment multiplier to engines would also be interesting if we ever get around to making reuse viable in KCT.
