### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by LuckyLuke997** [KSP-RO/RP-0#781]
delete

**Comment by KvaNTy** [comment]
That's because new tech tree contains only those parts which RO team had time to handpick for it. Not sure how NonRO parts issue is gonna be addressed in future, but I've made MM patch that remaps all parts from Stock/CTT tree into new one.

I tried to keep historical progression in mind, as far as it is applicable to CTT. Propulsion and construction branches are placed rather well. Not so sure about electronics branch, but at least those parts will be accessible in career.

[CTT_to_RP-1_Tree_Converter.zip](https://github.com/KSP-RO/RP-0/files/1409560/CTT_to_RP-1_Tree_Converter.zip)

**Comment by leudaimon** [comment]
@pap1723 should have more info, but afaik all mods that were placed in the old tree are supposed to be in the new one. At least that's what was discussed during the transition. Are these the only mods you had problems with, @winged7 ?

**Comment by pap1723** [comment]
Yes, as far as I could tell, all of the supported (and updated) mods were transferred to the new tree. Both of the above mods were not transferred however. There are probably a few others that I missed along the way.

**Comment by winged7** [comment]
@leudaimon Constellation Essentials is missing as well. I guess there are more missing mods but I can only mention three of these three because I worked on them.

**Comment by Bornholio** [comment]
https://github.com/Bornholio/RP-0/blob/patch-1/GameData/RP-0/Tree/Constellation_patch2.cfg

made a constellation patch, makes the strucutral for it 1B$2018, Engines are based on 2.8B$2018 about 1.5 times the Rover program total, the 68B is that same dev cost as the 68 engine itself is slightly higher

If i have time later i'll do the Space shuttle and B9

**Comment by winged7** [comment]
> If i have time later i'll do the Space shuttle and B9

I mean you can just copy values from old RP-0 tech tree rather than starting from scratch.
