### ISSUE TITLE
Earth Imaging Satellites contract uncompletable

### ISSUE THREAD

**Issue by borogove** [KSP-RO/RP-0#850]
The "experiment" ID is set to "mobileMaterialsLab" instead of "RP0-photos1" in Earth Imaging Satellites.cfg, which is frustrating to discover after spending an hour trying to fulfill the contract.

**Comment by leudaimon** [comment]
There is also another issue, the 24h counter starts ticking whenever you have a (new?) craft within the orbital parameters of the contract. This causes it to fail if you go for a different contract while this one is accepted.

**Comment by Tidal-Stream** [comment]
If I change mobileMaterialsLab to RP0-photos1 ContractConfigurator throws an exception. It seems to be incompatible with experiments containing dashes no matter how I escape them. Consider changing the names of the experiments from RP0-photos* to RP0photos. I can also confirm the 24 hour counter issue.

**Comment by Tidal-Stream** [comment]
Earth Imaging satellites are as interesting as communication and weather satellites and early space station concepts were mainly for Earth observation before the advent of advanced satellites. If we remove the contract only communication and weather satellites would remain. I would instead suggest removing the countdown timer and lowering the mission duration timer instead. There should also be a progression of contracts for the imaging level similar to weather satellites. Of course this would require renaming the experiments to the stock alphanumerical-only convention but luckily RP-1 is not released yet, and I think it is worth it. I would also suggest balancing payouts so they are similar to early weather sats for the first imaging level.

**Comment by pap1723** [comment]
The biggest issue with the contract is that the actual checking of the
parameters does not work. It never triggers when you properly approach the
target.

**Comment by Tidal-Stream** [comment]
This seems like a bigger issue. To test it I will try reverting both the film capsule and the contract to the stock mobile materials lab and see if I can complete it. The stock game already has contracts for temperature and pressure scan over a target so it should be supported - I will see if I can make it work.

**Comment by droric** [comment]
If the issue is ModuleManager crashing because the experiments have a dash(hyphen) in them, why not change the 4 or 5 config files for the photo experiments and remove the dashes and then change the experiment ID?  If this hasn't been thought of then I can give it a try to see if it resolves the issue.

**Comment by rsparkyc** [comment]
I'm going to mess around with changing the experiment type.  I also going to mess around with seeing if we can group some of the parameters to only activate the time if we know we have an imaging part on the vessel, which should prevent the timer from kicking off just because we got something else into orbit

**Comment by pap1723** [comment]
Contract has been made temporarily (at least until we can figure it out) disabled.
