### ISSUE TITLE
Launchpad sizing, launcher-classes and rollout costs

### ISSUE THREAD

**Issue by praymond-pbsc** [KSP-RO/RP-0#856]
A lot of people seems to have issues with the rollout costs, and while they are realistic, I believe a few simple tweaks could help.

Main issues I see are:
- Soviet needs to get to Level 4 for first orbital flight (sputnik) - this is not one, but 2 additional levels vs US who can get to orbit on a level 2 pad, or even level 1 with a Vanguard (tricky).
- Anything with a payload capacity above 40 ton, up to 140 ton and above needs the max pad - this is a range that will be filled by most custom launcher design (Heavy-Ultra Heavy), but also : Saturn 1B, Falcon Heavy, Space Shuttle, Energia, SLS, N1, Saturn V... the range is huge. 
- While the Falcon Heavy uses the same pad as the Saturn V used. However, the Saturn I/IB used complex 34, which I believe was a smaller pad, Falcon Heavy could have used that, it is in a similar class.
- As soon as you get to Titan IIIC/E, you need Level 5 pad!! Level 6 pad has no (or nearly no) US LV before the 90s that would use that I believe.

Main goals it should have:
- Not being able to launch orbital with Level 1 pad (exception of Vanguard that defies any scale)
- Try to reduce "unused" pad size and avoid double pad upgrade requirement playing US/Russia in terms of realistic progression.
- Keep progression in relation to realistic payload mass improvement
- Keep smaller pad useful in modern days for more efficient LV
- Keep similar progression, and same amount of Pads.
- Reserve the final pad size for anything bigger than Saturn V, so that there is a possible progression for custom LV.

Proposed changes:

OPTION A
- 150 step is removed, replaced by 1600 step, added 3500 step, other are slightly tweaked up/down.

Level | Mass Limit | Max Size | Avg Payload to LEO | Examples
------------ | -------------| ------------- | ------------- | -------------
1 | 15 | 10x20x10 | None | Early Sounding, WAC, Bumper, Vanguard (tricky)
2 | 75 | 12x30x12 | < 1 ton | Juno I/II, Thor, Vanguard (more likely)
3 | 300 | 16x45x16 | < 6 ton | Atlas, Titan II/IIIA, Delta II, R-7 Sputnik
4 | 650 | 20x55x20 | < 15 ton | other R-7s, Atlas V, Titan IIIC/E, Saturn I
5 | 1000 | 25x70x25 | < 40 ton | Ariane 5, Proton K/M, Delta IV, Titan IV, Falcon 9 (height)
6 | 2000 | 30x90x30 | < 70 ton |  Saturn IB, Falcon Heavy
7 | 3500 | 40x120x40 | < 150 ton | Space Shuttle, Energia/Buran, N1, Saturn V, SLS
8 | Unlimited | Unlimited | Unlimited | BFR

OPTION B
- 150 step is removed, replaced by 3500 step, other are slightly tweaked up/down.

Level | Mass Limit | Max Size | Avg Payload to LEO | Examples
------------ | ------------- | ------------- | ------------- | -------------
1 | 15 | 10x20x10 | None | Early Sounding, WAC, Bumper, Vanguard (tricky)
2 | 75 | 12x30x12 | < 1 ton | Juno I/II, Thor, Vanguard (more likely)
3 | 300 | 16x50x16 | < 6 ton | Atlas, Titan II/IIIA, Delta II, R-7 Sputnik
4 | 650 | 20x70x20 | < 15 ton | other R-7s, Atlas V, Titan IIIC/E, Saturn I, Falcon 9
5 | 1600 | 30x90x30 | < 60 ton |  Ariane 5, Proton K/M, Delta IV, Titan IV, Saturn IB, Falcon Heavy
6 | 3500 | 40x120x40 | < 150 ton | Space Shuttle, Energia/Buran, N1, Saturn V, SLS
7 | Unlimited | Unlimited | BFR

This makes pad 3 and up relevant all game, only the first 2 are automatic upgrades. Pad 3 can support Delta II and stay usable to modern times. You can still do a vanguard on Level 1 Pad... but by that time you most likely upgraded for larger Sounding Rocket contracts, so with research time and investment required, this is unlikely to happen, unless you want to grind "slower" than possible. 

Better Soviet Progression
- Pad 1 : Sounding rocket
- Pad 2: More sounding rocket
- Pad 3: Sputnik
- Pad 4: Vostok, Molniya, etc.
- Pad 5: Proton-K/M
- Pad 6: Nothing yet (Opt. A) / Energia/Buran, N1 (Opt. B)
- Pad 7: Energia/Buran, N1 (Opt. A)

The advantage is that I believe we could keep existing rollout costs and still stay close to reality, it would help incredibly large rollout costs early-mid game, especially as you need to go to Level 5 pad at Hydrolox most likely. Now only real heavy launcher will be in that Lvl 5+ costly category. Now Saturn V has a big rebate tho, going down 1 level... but it is so big, so many part and costly, that rollout costs should be huge anyway. 

Option A retains Saturn V rollout costs in line at Level 7 pad. Option B reduces it at Level 6, but might be more efficient with the same amount of levels as of today.

**Comment by asmi84** [comment]
Tiered launchpad limits don't make any sense as in reality they are built and sized for the LV that is to be launched from it, not the other way around. I'd get rid of these "tiers" entirely and allow to enter the limit the pad is to be upgraded, and come up with the formula to calculate the price of such upgrade and the time required depending on a difference between current pad limit and new one being requested. I'd also provide an option to reduce upgrade time at expense of higher price. This will more closely reflect reality as throwing more money at a project does reduce construction time (up to certain point).

**Comment by ec429** [comment]
That's an idea I've been toying with too, except I wonder if maybe rather than upgrading an existing pad you always build a new one of a specified size.

**Comment by pap1723** [comment]
Always building a new one would make more sense to me.

**Comment by Karhgath** [comment]
That's not a bad idea. It's the upgrading part that does not make much sense. It's not 100% true that they are always built for a specific LV (e.g. falcon reusing saturn V pad) but they are probably heavily retrofited.

So maybe just no upgrades, you select the size to build, maybe add more tiers so that you must choose - do I pay a bit more to have more flexibility in the future or not. You would still need to come up with decisions like today, and it must not be a false choice or it won't add anything.

**Comment by PhineasFreak** [comment]
To retrofit a pad for a new launch vehicle (even if using the same propellants) you will have to remove and rebuild almost everything except the major concrete structures (examples: CCAFS SLC-37 & SLC-39A, VAFB SLC-6).  So, it does not sound too bad to have to make a new (custom) pad for a new launch vehicle.

**Comment by NathanKell** [comment]
Just a quick note, the pads were sized as:
V-2 / Vanguard, 20t
Thor / R-5 (the Soviets could have gone to orbit on R-5 + kick stages), 60t
Atlas / Titan / Kosmos / etc., 150t.
R-7 family, 350t
Saturn IB, 600t (note Saturn IB was only ~580t on the pad! Not much more than Saturn I)
Proton / Saturn C-3, 1200t (note Proton is about 800t)
Everything else

It might be worth upping the 1200t tier to 1600t to support F9H-class LVs, but I'm not convinced.

I of course support, in theory, one-pad-per-LV, I just have no real idea how we could do that given how KSP does parts. It's the stage-detection problem all over again, just worse because we have to know what the booster core is!

But not allowing upgrades and instead building a new pad in place...that I like, and that's very possible with some KCT-munging. Worth going for indeed!

As to Sputnik vs. later R-7s, the problem there is that you're looking at only, what, 10t difference between R-7 and Vostok, all up? Very hard to discriminate, there. I actually tend to like the balance it gives the Soviet playthrough--you have to invest a lot in infrastructure, but once you do you're golden for years and years (and it balances out the cheaper parts and better engine tech).

**Comment by asmi84** [comment]
Soviets/Russians always overbuild their pads to provide a safety margin as well as allow for a future upgrades of the launch vehicle (which tend to increase GLOW). I seem to recall that Angara pad was designed to withstand two times the GLOW of Angara-A5 in maximum configuration (with H2 upper stage), the pad for Zenit is even more over-engineered - AFAIK it was designed to support almost 3 times the weight of a vehicle as there were quite big upgrade plans for the vehicle.
I couldn't find any numbers on a Soyuz pads in my quick search, but I totally expect similar big design margins. At very least it needs to withstand about 4.2 MN of liftoff thrust (Soyuz LVs have high liftoff TWR of over 1.3).

**Comment by Bornholio** [comment]
Add **new feature** label, probably not happening unless a very ambitious KCT programmer takes over

**Comment by siimav** [comment]
Launch pads have been un-upgradeable for a while already. Now building them at custom sizes got implemented in #1580.
