### ISSUE TITLE
Crew Training for RN Soyuz (PR-1)

### ISSUE THREAD

**Issue by oltarzewskt1** [KSP-RO/RP-0#858]
The RN Soyuz 7k capsules (descent and orbital module) don't allow Kerbals to launch when they have Soyuz proficiency and mission training. There appeared to be a small problem in RP-0/CrewTrainingTimes.cfg, where these capsules had their part names listed with hyphens instead of underscores (shown below), but changing this did not resolve the issue.

// Soyuz
	Soyuz = 200, MatureCapsules									// 600
		SSTU-SC-A-DM = Soyuz
		SSTU-SC-A-OM = Soyuz
		rn-zond-sa = Soyuz
		rn-lok-sa = Soyuz
		**rn_lok_sa = Soyuz**
		rn-lok-bo = Soyuz
		**rn_lok_bo = Soyuz**
		t-bo = Soyuz
		t-af-bo = Soyuz
	Soyuz-Mission = 60

**Comment by Karhgath** [comment]
I just sent a pull request with my changes, I had the same issues.

The RN 7K-OK Descent Module is named "sa-ok" and not "rn-sa-ok", and there are the 2 Orbital Module Male/Female names "sa-bo-male" and "sa-bo-fem".

The underscores "_" are auto converted to dashes "-", so that is not actually an issue.

This fix is working for me and I'm able to use the same training for all RN Soyuz parts.

See https://github.com/KSP-RO/RP-0/pull/859

You can apply those to your copy for now.

**Comment by oltarzewskt1** [comment]
Awesome, that fix worked for me, thanks!
