### ISSUE TITLE
RELEASE v0.55 for KSP 1.3.1

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RP-0#865]
Shall we release current master RP-0 to 1.3.1 and get ready for further changes towards RP1 and KSP 1.4.X?

Any objections/seconds/insights?
@pjf @jwvanderbeck @ec429 @lamont-granquist @NathanKell @raidernick @rsparkyc @pap1723 @PhineasFreak @stratochief66 @aw1621107 and anyone else contributing.

**Comment by PhineasFreak** [comment]
From a compatibility standpoint it would make some sense to release a KSP 1.3 compatible version of RP-0 to complement RSS/RO. But, do we really need to do so? RP-1 is playable and the only way to improve upon it would be to release it officially and let everyone test it and find it's shortcomings/bugs.

Now that i think about it, it would be even better if we could adopt a release system like Principia. Even better, time them so that RO/RP-1/Principia are all released in the same time frame (RSS fortunately does not require monthly updates!).

**Comment by raidernick** [comment]
RO definitely needs monthly updates and I plan to do that, waiting a year or more between releases is unacceptable especially with the number of changes we get daily there. I assume the same can be done here but I can't comment on the RP0 vs. RP1 issue as I don't use either mods.

**Comment by aw1621107** [comment]
I think I agree with @PhineasFreak. If we're going to be moving on to RP-1, releasing a final version of RP-0 means we have to deal with at least one more release cycle of support for an older version that we don't really play (or so I assume). It's been such a long time since the last release that I think players wouldn't be that surprised that they would need to start a new save anyways. It's probably also better for RP-1 testing to have everyone use the same version.

I also agree on the regular updates part. I would vote to release at the same time as Principia, so players can upgrade everything at once.

**Comment by Bornholio** [comment]
Given almost all interest is in RP-1 i'd say we have consensus that developmental is the forward release path.
I think an unsupported 1.3.1 RP-0 is still worth the time since it allows for non save breaking update.

**Comment by pap1723** [comment]
This has obviously been resolved and moved to RP-1
