### ISSUE TITLE
Early career engine and avionics balance

### ISSUE THREAD

**Issue by Herrkurt** [KSP-RO/RP-0#877]
This is an analysis of options for historical first orbits in regards to career balance and the usefulness of the NAA-75-110 A-7 config and the X-405 which Pap suggested I post as an issue.  The A-7 and X-405 are in the same node as significantly more powerful engines.  From the historical view this makes sense because these engine debuted in the time period encompassed by that node and it would make sense in game-play as well if their historical payloads, the only things light enough for them to launch, did not require significant additional investments in research time to unlock.  When compared to a historic Sputnik launch on an R-7 a Juno I launch of Explorer 1 requires three additional technologies: '56-'57 Solids, satellite era electronics and early avionics.  A historic R-7 Sputnik mission can be launched without the R-7 sized avionics because the R-7 used to launch Sputnik had its inertial guidance system removed.  To create something close to parity for a historic US first orbit I suggest that Explorer 1, and possibly Vanguard 1, be moved to the same tech node as Sputnik, prototype avionics.  The Juno I Explorer 1 mission would still require the additional research of '56-'57 solids but the availability of Explorer 1 as an ultra-light payload would make the Juno I attractive as a lighter and possibly cheaper route to achieving first orbit.

**Comment by Schnobs** [comment]
First off...

As I understood @NathanKell way back when, "Avionics" isn't merely guidance. It's supposed to represent everything that's necessary to control a rocket, like the sensors and mechanisms necessary to maintain tank pressure, or opening the right valves in the right order to start up the engine (and shut it down again once fuel runs out). If you remove gyros and give directions by radio, you still need a lot of gear on the rocket to make it actually go where you tell it to. As a matter of fact, most of that gear is necessary to make it go at all.

Avionics starts with the heavy, relais-driven electrics that controlled the A4 and progresses through transistors to microcontrollers.

Most prefab rocket tanks have avionics to fit their mass. If you assemble (say) a Titan-II from FASA parts, it will come out just as heavy as the real Titan was, and work out of the box without the need to stick on any avionics modules. You still need at least a probe core or something else that provides "Control" in the KSP sense, but that's another topic.

Avionics was introduced to add an approximately fitting amount of dead mass to procedural vehicles, depending on how far you have progressed in electronics research.

---

That said, I just notice that in the new tree, prefab tanks no longer depend on avionics research. I can unlock and fly a Titan-Centaur without ever spending a single research point on avionics; if I had a soviet part pack, I could probably do the same with the R-7 or Proton. I consider this to be a severe problem. @pap1723 ?

Finally, to the topic at hand: I think it should be the opposite, Able and Sputnik moved one node higher on the tech tree.

Historically, lots of things became possible all at once. Within a year after Sputnik, satellites carried solar panels and probes went to the Moon and beyond. Instead of moving all of these parts forward, I'm more inclined to see the Sputnik (and Able) as the odd one out and move it back. Thus Satellite Era Electronics would become a prerequisite for any satellite.

As to the Explorer needing extra Solid Rocket tech, I'd like to point out that the R-7 requires a much bigger and more expensive pad. I'm not sure how the construction time compares to research, but am afraid that it's not in the R-7s favor.

**Comment by Schnobs** [comment]
> the A-7 and X-405 are [...] engines for orphan launchers

Well, I don't think this can be helped. IRL several agencies developed rockets, each for their own needs and purposes. But in the game we're but a single agency, with a much better plan than they could ever had. Regardless of early payloads, a quick look at the tech tree reveals which engines will have a future and which don't.

(BTW, you *can* put a sounding rocket core into orbit on "Basic Rocketry" Launchers + Tank-II)

**Comment by pap1723** [comment]
@Schnobs The change for avionics unlocking happened because of Procedural Avionics. You no longer need to unlock the "Saturn" avionics because you can use the procedural avionics (if you want) along with any other type of tank.

@Herrkurt What is the ultimate proposal, that the Explorer 1 and Vanguard 1 move to the earlier technode?

**Comment by Schnobs** [comment]
Just received a notification for this... I'm so out of touch it's untrue.
@pap1723 
The possible problem I spotted were integrated avionics: Parts that are nominally tanks but have avionics capabilities to suit their mass. This allows (allowed?) the player to only research the tank, and immediately fly it without doing any avionics research at all.

For practical purposes, I think this mostly matters with the Atlas tank. If that's even still applicable. As I said, I'm totally out of the loop.

**Comment by pap1723** [comment]
@Schnobs yes, that is an issue with the LEGO idea with the FASA parts currently. The avionics are baked into the tanks because there isn't a part that would attach to properly.

**Comment by NathanKell** [comment]
The avionics are tech gated. We fixed the problem back then. :)

Sent by my thumbs, slowly.

**Comment by pap1723** [comment]
The whole first part of the game has been re-balanced so this no longer applies.
