### ISSUE TITLE
MM found errors from "RO/RO_suggestedmods/RO_RCS_Config.cfg"

### ISSUE THREAD

**Issue by kurgut** [KSP-RO/RP-0#884]
First thanks to bring this amazing stuff to the game, couldn't play without it! :) 

I'm trying installing RO/RP-1 (following AKA spreadsheet)

I've got 2 errors found by MM on loading as in the title of the post, is it impacting the game?

Thanks

**Comment by Brummi1234** [comment]
Hi kurgut,
something could be broken, because mm does not know what to do with these configs.
Maybe you will never notice something, because you don't use the parts, maybe there will be gamebreaking bugs.

I believe someone else on the discord had the same problem and for him it was stock configs for realfuels (or real plumes, i don't remember).
Just look up your game data folder and see if there are folders for mentioned things and then delete them

**Comment by kurgut** [comment]
Hi Brummi, thanks for reply, yes as you say until now I'm able to play the all the stuff fine. And yes, I already checked my gamedata folder, but decided not delete those files until they cause a real issue, or not!

**Comment by jwvanderbeck** [comment]
Without a proper log file it would be impossible to know what is actually causing the error.

**Comment by kurgut** [comment]
Hi, sorry for late reply, this was fixed with new updates. :)
