### ISSUE TITLE
Null reference exception appearing to originate from CrewHandler

### ISSUE THREAD

**Issue by Wrecker15** [KSP-RO/RP-0#892]
Received a nullreferenceexception upon trying to recover a vessel to SPH from the runway after a short flight and landing. This locked up all attempts to change scene or save. There was no issue with recovering from runway before starting the engine. 

You can look for the start of the pertinent info by searching for "Bonanza Loaded" in the output log below:
[output_log.txt](https://github.com/KSP-RO/RP-0/files/2320764/output_log.txt)

Here is KSP.log too. Issues come up at 09:54:34.826
[KSP.log](https://github.com/KSP-RO/RP-0/files/2320775/KSP.log)

Mods (other than those recommended/required by RP-0):
AtmosphereAutopilot
KAC
RSSVE (and its requirements/recommendations)
FASA
ShipManifest
[X] Science!
RasterPropMonitor (and Core)

I'm hoping it may just be a mod acting up. But I wasn't too sure because it appeared that the logs referenced RP0. Thanks for the help!

**Comment by droric** [comment]
Is it possible to repeat this with a minimal amount of modification and with a new career save file?  Given the additional unsupported RP-0 mods there could be a conflict that won't show up for 'normal' RP-0/1 installations.  Troubleshooting is easier if it can be narrowed down to only a few mods.

**Comment by Wrecker15** [comment]
I believe the issue originated from ship manifest not working correctly
with kct recovery. I have since gotten it to work without ship manifest.

**Comment by droric** [comment]
I am running into this exact same bug.  I don't have ship manifest installed.  I have attached my output_log.txt as well.  Another user in the Discord has also encountered this bug.  Even creating a new vessel with only the Bonanza part causes the issue.  I noticed the Bonanza does not validate that the crew is properly trained before allowing you to launch the vessel.  Even if I train the crew with proficiency and mission training before starting the flight the bug still occurs.  I feel that might be the root of the issue.

[output_log.txt](https://github.com/KSP-RO/RP-0/files/2409243/output_log.txt)

**Comment by droric** [comment]
This appears to be caused by HyperEdit.  Once I removed it from my Gamedata folder the broken craft would launch and recover correctly.

**Comment by droric** [comment]
So I believe this is actually a corrupt persistent.sfs file.  I was able to resolve it by using Alt-F9 to load my persistent save game file after the craft was in the bugged unrecoverable state.  I then went to mission control and deleted the WBI Tourism contracts that were set to visit my bugged plane.  Somehow it seems when flying my plane it sees it as a space station and that it wants me to have tourists visit it?  I will do more testing tomorrow when I have gotten more sleep but I ran another test flight afterwards and I was able to fly the craft, land and recover, which is further than I have gotten on troubleshooting.  I noticed my 3 yellow suit astronauts also have a bugged/corrupt state since they are not on leave yet they can't be trained for the vessel I want them to fly.  The 4th yellow suit astronaut is MIA, lost to the kraken.  I'm not sure my save can be fully recovered at this point but I believe I reloaded module manager which may have caused this to occur in the first place.  Note to self, don't test things on your career save...

**Comment by pap1723** [comment]
Can this be closed now? It is not an RP-0/RP-1 issue, but a corrupted SFS issue?

**Comment by droric** [comment]
I don't see why not.  At worst if this occurs again or was misdiagnosed then we can reopen the issue.

**Comment by mystickerbal** [comment]
I can confirm this happens in the released RP-1 version as follows for me: for some reason, after breaking  9000 m/s manned record (which I did while going for Moon fly-by and orbit), kerbals begin to disappear in the TextureReplacerReplaced (one of the few ways I can see all kerbals in flight) , as well as in the save file and this error NullReferenceException KerbalRoster.ValidateAssignments. happens a lot in the log. Ultimately, you end up with just 3 kerbals in the roster. Sometimes, even the main buttons like save, quit, space center lose functionality after this happens.

This happened to me in two completely different careers unrelated to each other at the exact same stage (9000 m/s manned). How I corrected is I changed the game settings to no longer have any kind of WBI contracts. This game is not about friggin tourists anyway!
