### ISSUE TITLE
Suggestion for tooling: Treat rounded-off increments as cheap "off the shelf" without tooling

### ISSUE THREAD

**Issue by GavJenks** [KSP-RO/RP-0#895]
For example, for a given tank, WITHOUT tooling, the procedural costs could go:
diameter:

1m = $300
1.1m = $3,100
1.2m = $3,200
...
1.9m = $3,900
2m = $400
2.1m = $4,100

and so on. By tooling, it brings the 1.9's and 2.7's down to reasonable prices afterward, but doesn't do anything at all to the rounded off diameter sizes. Thus still allowing you to use procedural parts along with their upgrade types and texturing, etc., but still capturing the same challenges and design constraints of choosing between custom and "off the shelf" options.

**Comment by droric** [comment]
Not sure what the point of this is except to restrict what types of rockets you can build if you want to keep the costs down.  I think this is an interesting idea but doesn't really fit in the RP-0 realistic world.  In the real world there was no such thing as an 'off the shelf' rocket fuel tank in the 50s.  They all had to be engineered and designed to specifications.  I would suggest increasing the funds payouts if you want things to be easier to obtain or cheaper.

**Comment by GavJenks** [comment]
Well then why are there dozens of non procedural tanks available right now in RP1 for small fractions of procedural costs?

Off the shelf is already in the mod. This is a suggestion how to alter it not add it.

**Comment by droric** [comment]
The non procedural tanks cost more to unlock than the procedural parts cost.  The reason is the 'prefab' tanks include the tooling costs when you unlock the tank.  Off the shelf is not in the mod as the development costs are factored into the unlock costs on the parts. 

The Saturn V fuel tank costs 20,000 funds to unlock and has a parts cost of 608 funds.  A procedural tank of the same size costs 27,000 to tool and costs 100 credits once tooled.  So the procedural tanks are cheaper with a slightly higher up front cost..  Based on the dry mass values of the Saturn V tank we can assume its using Procedural Tank 1 which has lower tooling and end costs.

**Comment by GavJenks** [comment]
All the procedural tanks ALSO cost a bunch to unlock, though. So I don't think that's the logic being intentionally used here.

Procedural tank = high unlock, high tool cost, cheap marginal cost

Fixed tank = high unlock, zero tool cost, cheap marginal cost

**Comment by ec429** [comment]
GavJenks: the fixed tanks are supposed to cost _extra_ to account for the missing tool cost.  If they don't that's a balance/cfg bug that we want to fix by increasing the fixed tank unlocks, _not_ by changing the proc tooling costs.

**Comment by pap1723** [comment]
This is what needs to happen, and it was a process that was started a while ago, but requires a lot of work:
* Someone needs to go through the pre-fab tanks we have in RP-0 and measure the sizes of them, the length and diameter
* Then, those tanks need to be put into one of the current ProcTank categories
* Finally, the same size ProcTank needs to be built to know what the cost and tooling cost would be for it

The total of the cost of the tooled tank becomes the cost for the prefab tank. Then the total of the tooling cost becomes the total of the entryCost for the prefab tank.

Anyone want the job?

**Comment by Standecco** [comment]
What I had done with prefab tanks was tool an equivalent procedural tank and then use the other tank, since their unlock costs were negligeable. Would it be possible to add the tank tooling for equivalent sizes when purchasing prefab tanks, since their entry and tooling costs would be equal.This would allow switching from one part to the other and allow for the 4% flexibility. One should not be penalized for using prefab tanks nor should they cost less money.

**Comment by pap1723** [comment]
@Standecco now with knowing how the tooling works, we "might" be able to add a PartModule to these and read that part module to have the tooling added / accepted that way. I will reference this in #931
