### ISSUE TITLE
science points balancing

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#897]
Hi all,

I get the feeling that the current settings for science affect game balancing. I just did a simple flyby of vesta, with some of the science experiments on level 2, but not even all, and I gained about 900 science points. This way you can probably get anywhere in your research by just flybys of every body between Venus and Jupiter (including both + moons) (tbh, I didn't check, but this seems to be a valid guess.) 

Maybe we should reduce the science points for space for everything beyond Mars?

**Comment by ec429** [comment]
Have you looked at the science costs later in the tree?  The problem, in my opinion, is not excessive science from planetary probes, rather that the latter part of the tech tree lacks parts (which in turn is because rather few new launch vehicles were developed in the '80s and '90s...).

(I mean, maybe planetary science could stand to be cut by 5 or 10%; but I'd say no more than that is needed.)

**Comment by glilienthal** [comment]
Still thinking about that, last Io flyby gave me about 1600 Science..  At least for now I am never science point limited, it's always money and time.

**Comment by pap1723** [comment]
@glilienthal Any thoughts on science values now?

**Comment by Bornholio** [comment]
I think i agree, its a tough uphill climb past lunar, but once you hit venus and mars you get huge bursts of points.  Hard mode mitigates this some. Offset for later points is just the time delay of getting to the outer planets.

**Comment by pap1723** [comment]
Obviously as more players continue to play, we will continue to look at science values.
