### ISSUE TITLE
Let's place/price some parts, yo!

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#90]
From discussions in #57 , it's clear we want to place/price some parts. Here's a list of things we can do to help that:

- [x] Figure out how much wings are. We've got heaps in the starting node, and they're all 500 spacebucks each.
- [x] Sweep parts from modified nodes (eg: hydrolox engines) to new nodes, before the RP-0 parts are placed.
- [ ] Make the orphans node visible, similar to how it was in RPL. This gives us a visual indicator of parts in-game that we know we need to place or remove.
- [ ] <s>[.](https://www.youtube.com/playlist?list=PLFC4EE4355ADEBDB1) (Controversial) If we've got a rough idea of the exchange rate between kerbobucks and 1950s dollars, run a final pricing pass over non-RP0/RO parts which adjust their prices. They're still going to be wrong, but on average they'll be less wrong.</s>

**Comment by pjf** [comment]
For wings, I'd suggest no research costs (being in the start node, they don't get these anyway, do they?) and... I dunno, $20 each? Or whatever they cost approximately in pWings, which has always been cheap enough that I've not cared.

**Comment by NathanKell** [comment]
Your wings idea sounds 100% correct to me. Ditto sweeping. If making Orphans visible is useful, sure; I generally find the names alone enough, and do the placing/pricing out of KSP...

While RL is currently overbearing (ask around on #ro if you missed the updates), I'll try to pitch in when things calm down.

On the last point, the problem here is this. Imagine a space program where human spaceflight capsules are cheaper than small-rocket lifter engines, where fuel tanks cost more than both, and where structural girders are as expensive as engines.
Congratulations, you've imagined stock KSP ~~balance~~.

I actually did try once, and you can get decent *total* costs working out OK (like, say, for the Apollo CSM and lander), but the payload : LV ratios will be off, and the relative costing of parts will be...nuts. Sorry. :(
