### ISSUE TITLE
Dec 1 developmental notes

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RP-0#916]
A few parts showing in both start and purchase parts nodes, thermo barometer for example with latest developmental (as of this morning).
EHSFSciencec node Magnetometer boom and rpws antenna lack science experiments, seeing a couple other duplicate parts spread in science nodes.
The colored mod source in description not showing.

**Comment by pap1723** [comment]
The duplicated parts are from ORPHAN parts not being removed by the new Tree generating the script. The same is the issue with those science experiments you saw. They should not exist as they are the actual DMagic Experiments, not the modified RP-1 ones.

The colored mod source was an issue with a typo, will be fixed in the next upload.

THANKS FOR FINDING ALL THESE!!
