### ISSUE TITLE
Crew retirement not updated when recovering astronaut from space center

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#937]
From discord:
>  if I'm controlling an astronaut walking around on earth after a flight, and Recover him, his retirement date gets updated. if instead I return to the space center and recover the astronaut from there, retirement date isn't updated.
> had 2 astronauts. recovered both from space centre, neither got updated; recovered both while controlling them, both got updated; tried one each way, only the in-control recovery got updated

Note this is with astronauts having exited their craft and walking around on their own; I didn't try with astronauts inside a craft.

**Comment by pap1723** [comment]
Can anyone recreate this one?

**Comment by siimav** [comment]
Yeah, I can confirm this bug. It always happens when recovering vessels from the tracking station and is not limited to only nauts on EVA. My quick investigation revealed that the `GameEvents.OnVesselRecoveryRequested` event is not fired when the recovery is done from tracking station. It's possible that some other event should be should be used in this case but it might be that not all the required data is available for these. Possible candidates are:
```
onVesselRecovered
onVesselRecoveryProcessing

**Comment by NathanKell** [comment]
If memory serves I only ever needed the protovessel stuff, so any of the events should do, it shouldn't need the live vessel.

**Comment by rsparkyc** [comment]
I just tried binding to the `onVesselRecoverd` event, but it shows no crew (perhaps the crew was already removed by the time that event was fired).  I'll try `onVesselRecoveryProcessing`
