### ISSUE TITLE
Real ISRU integration

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RP-0#943]
https://docs.google.com/spreadsheets/d/17ulTbJnPmblfDJGvcCpdOPLJTStC7Y1NQvOwVKG3TVg/edit#gid=303749319

Starting work on tech placement and pricing.

Nasa's research expendature on ISRU related science has been 1.45B over the last 9 years.
This is hard to reduce down to hardware development so any citations would be helpful
Would also like to add kilopower during this.

If you want edit access to the list please ask here and then in GS  got a lot of access spam on the golden sheets so i ignore it.

**Comment by Bornholio** [comment]
Like magic, Kilopower was added, if interested use starwasters fork

**Comment by pap1723** [comment]
https://github.com/Starwaster/RealISRU

**Comment by winged7** [comment]
>  The 40 kW model weighs 7.2841t,

That heavy? The 60 kW NASA SAFE 400 which I use for many vehicles or ISRU facilities weighs only about 1000 kg (1800 kg with radiators) and it it supported by RO: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/NearFutureTechnologies/RO_NearFuture_Electrical_Nuclear.cfg

What makes such a big difference in mass?

**Comment by Standecco** [comment]
> What makes such a big difference in mass?
From what I've read from the papers, that difference comes from the fact that those figures are probably missing shielding. It could also just be that SAFE is a way superior design, but I see that as unlikely. I'd suggest tuning down Kilopower's mass but that SAFE-400 from NFT is probably unbalanced (read: unrealistic). Nuclear reactors will always have way worse W/kg than solar panels due to their very nature and the required shielding.

**Comment by pap1723** [comment]
This has been done for RP-1 integration in the tech tree. Is this still a useful issue to have open?

**Comment by Bornholio** [comment]
closing
