### ISSUE TITLE
Contracts Payouts

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#948]
There has been a lot of discussion on Discord about the contract payouts. Especially things like sounding rockets can be spammed to a crazy high payout if the player is willing to grind.

We absolutely need to put a MAX cap on the payouts of the contracts, especially the Difficult ones. 

At the same time, it appears that some of the satellite contract payouts are a little low.

**Comment by siimav** [comment]
Putting a max payout in place makes sense  for preventing abuse of the sounding contract system. But I think we shouldn't reduce sounding rocket rewards too much for people who play normally. Otherwise it may cause an even bigger grind for the pre-orbital era. Also, since we don't have any yearly budgets, SR contracts may be the only ones that are available for getting funds at various points of the career.

**Comment by Serina0** [comment]
A cost/effort thing does need to come into effect, as if you can make more money off of a sounding rocket rather than having to launch a satellite and put it into orbit (especially if it's a specific orbit), A Sounding rocket is basically, just fly straight up and stage, giving the payout on reaching an altitude. The cost of the vehicle is also somewhat lower (although I can only assume they approach orbit capability at some point, they're just faster and easier). 

To alleviate the issue I have the following suggestions:

- Set a maximum amount of sounding rocket payout depending on the difficulty setting.
- Increase advance payout and deadline length for the First artificial satellite on lower difficulties. 
-Figure out: Why do "normal" people need to grind the science rockets? Make changes accordingly


From what I know, the reason min-maxers spam them is to buy more upgrade points, which shouldn't be the case for the normal user that might not care as much for the amount of time spent.

**Comment by NathanKell** [comment]
The point is basically no one *needs* to grind them. But if you have a
choice between gaining no money while waiting for something to unlock, and
gaining money (which can then be spent to make the thing unlock faster,
too!) then the optimal choice is obvious.

The solution here, IMO, is less stick and more carrot. Instead of figuring
out ways to make that grind unworkable, automate it. If you have a free VAB
line, let it generate money for the player (based on their tech level, and,
optimally, things they've done before, i.e. demonstrated vehicle design
capability for mission x, allow automating mission x).

At the simplest, such a system would just give you x money per month for
each VAB line left not doing things, where x is a function of build rate
and tech level.

**Comment by Serina0** [comment]
The above suggestion is good but won't it require creating an entirely new system?

**Comment by Bornholio** [comment]
We had a cycle of this before.  did the fix for excessive SR payouts get unset?

**Comment by pap1723** [comment]
Addressed in #956
