### ISSUE TITLE
Early Game Reorganization

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#956]
This has been a moving target as we try to determine the best playthrough structure. Here is the latest proposal:

**General Progression of the Early Contracts:**
FIRST LAUNCH --> KARMAN LINE --> Sounding Rockets (Horizontal Distance) --> FIRST ORBIT

**SOUNDING ROCKETS**
- We do away with the Difficult, Intermediate and Hard Sounding Rocket contracts. In it's place we have a Sounding Rocket (Payload) contract
    - We use a system based on @leudaimon proposal here: https://github.com/KSP-RO/RP-0/pull/955 and also using the Altitude records to keep the targets achieveable
    - This allows us to control the payouts easier by keeping the payloads small until more tech nodes are unlocked.
    - These contracts will have no cooldown period at the beginning, however, upon each completion of a contract, the cooldown period will increase by 1 or 2 days (TBD through playtesting)
    - The contracts are no longer offered after the acceptance of the First Orbit contract
- We eliminate the progression of repeating Altitude Sounding Rockets
    - We currently have the "Records" contracts that are automatically accepted and provide monetary bonuses when the altitudes are achieved. Previously, the SR (Altitude) contracts could be milked for the most money by only just breaking the current contract record and not going any higher. This led to more payouts (not intended) and increased grinding for the most potential money.
    - The Sounding Rocket (Altitude) contract now becomes a single contract for 2000km (TBD through playtesting) that does not have an expiration date. Now there is not a penalty for trying to get the highest altitude record you can as you will still get the payouts from the above "Records" contracts
    - Once you have reached the target altitude of the contract, the contract is complete and the Sounding Rocket (Altitude) contracts are finished.
- We add Downrange (horizontal distance) Sounding Rockets
    - With the awesome new system from @siimav that lets us measure the horizontal distance traveled during a launch, we create a "Records" system that is similar to the Speed and Altitude records that already exist.
    - We create a single Sounding Rocket (Horizontal) contract that has a distance requirement of a suborbital flight that gets at least 5000km (TBD through playtesting) downrange. You will still gain records for the other distances covered, just like Altitude and Speed records.
    - **Completion of this contract unlocks the First Orbit contract**
- Add a Sounding Rockets (Repeating) contract
    - This is a repeating contract that is designed to be a "bailout" if you need funds in a pinch. Having something like a 10-30d cooldown (TBD from playtesting) it should not be able to be used as a grinding tactic, just a quick, we need money now mission.
    - We will use the setup from the current Sounding Rocket (Intermediate) contracts with a capped maximum payout

**FIRST ORBIT**
- Currently, there is a lot of money that is given as the advance for the First Orbit contract. This was designed to let you build the infrastructure that you needed in order to get to orbit.
- With the contract now being gated behind further progression, that advance might come too late and may cause the player to have to wait too long to be able to upgrade facilities.
- With that in mind, the large advance will be split up into the reward for the Sounding Rocket (Horizontal) contract completion and the advance for the Orbit contract. This lets you get started on building your upgrades before committing to accepting the contract and ending your Sounding Rocket missions.

The overall goal of structuring the contracts this way is to continue to allow for progression. Get horizontal distance means a lot more to getting into orbit than carrying heavy payloads to an arbitrary altitude. It should structure things in a way that do not require a huge grind if not wanted, and can direct new players, or less experienced players as to what they should be trying to do go progress. By putting a increasing cooldown on SR contracts, it should provide more money up front and less as you progress to make grinding those SR contracts much less appealing and pushing players to orbit and beyond.

**Comment by ec429** [comment]
> This stops a player from launching a sounding rocket telemetry unit into orbit and calling it a satellite.

Why?  Sure it's an even less useful satellite than Sputnik 1, but it's a viable way to prove "look, we can put things in orbit" since it's got a transmitter inside it.  It's basically "Sputnik 1 but the battery only lasts half an hour".  Which is probably _longer_ than the 55kg Upper Stage proc avionics lasts, and you're still allowing that.

(I mean, personally I never would try to make orbit without Avionics Prototypes, but saying "no you can't" just seems weird.)

Re the sounding rockets, I still don't see why we can't just have a "decrease payout based on # of SRs completed" to replace the current "decrease payout on # of techs"; it seems like much less work for us than what you're proposing.  Having read through all the discussion on Discord I don't recall seeing any reason why that wouldn't solve everything.

Your two points about planes at the end seem fine.  Though note that the X-Planes (Low) contract is subsonic and Junkers cockpits for that are reasonable.

**Comment by leudaimon** [comment]
Nice ideas in general. A few comments though:

About tech gating, I would rather see the game mechanics incorporating these things. Tech gating seems too artificial.
In that sense:
5. Require the craft to transmit science after 1h:30 (representing telemetry that the craft is indeed in orbit) would prevent people to reach orbit on a SR core, while still giving flexibiliyy
5(two 5s?!) and 6. Why not giving the cockpits properties that make the crazy contraptions unusable? Removing the vacuum capability of the early cockpit goes a long way in that direction.

**Comment by pap1723** [comment]
> > This stops a player from launching a sounding rocket telemetry unit into orbit and calling it a satellite.
> 
> Why? Sure it's an even less useful satellite than Sputnik 1, but it's a viable way to prove "look, we can put things in orbit" since it's got a transmitter inside it. It's basically "Sputnik 1 but the battery only lasts half an hour". Which is probably _longer_ than the 55kg Upper Stage proc avionics lasts, and you're still allowing that.
> 
> (I mean, personally I never would try to make orbit without Avionics Prototypes, but saying "no you can't" just seems weird.)

You are not wrong, I am just looking for ways to stop orbit inside of the first year. This at least delays the huge bonus. It might not be worth it, I want to hear what everyone says.

> Re the sounding rockets, I still don't see why we can't just have a "decrease payout based on # of SRs completed" to replace the current "decrease payout on # of techs"; it seems like much less work for us than what you're proposing. Having read through all the discussion on Discord I don't recall seeing any reason why that wouldn't solve everything.

You might be right about that being the easiest way to fix it. Can you think of a way to inform the player that they are at x number of launches?

> Your two points about planes at the end seem fine. Though note that the X-Planes (Low) contract is subsonic and Junkers cockpits for that are reasonable.

That seems like a strange contract that we should probably remove. No reason to have a subsonic flight that is gated by a supersonic flight, should we?

**Comment by pap1723** [comment]
> Nice ideas in general. A few comments though:
> 
> About tech gating, I would rather see the game mechanics incorporating these things. Tech gating seems too artificial.
> In that sense:
> 5. Require the craft to transmit science after 1h:30 (representing telemetry that the craft is indeed in orbit) would prevent people to reach orbit on a SR core, while still giving flexibiliyy
> 5(two 5s?!) and 6. Why not giving the cockpits properties that make the crazy contraptions unusable? Removing the vacuum capability of the early cockpit goes a long way in that direction.

My concern with something like requiring transmission of science after 90 minutes is the Contract Configurator concerns. The duration parts of many missions are broken at times and a contract like this seems to be asking for issues.

What properties can we use to make the cockpits unusable like that? Getting to 100km doesn't mean anything to KSP so the Karman Line can be achieved by any cockpit. The Unpressurized flag will be set for the no entry into space, but I don't know another way to limit the 100km setting.


On a separate note, why does tech gating get so much hate when the Orbital Reentry has been gated forever in RP-0?

**Comment by ec429** [comment]
I think the Unpressurised Cockpit limit is 50km, not space.  So that should be fine.

> Can you think of a way to inform the player that they are at x number of launches?

Why do they need informing it?  All that happens is that the payouts start shrinking, there's never a hard cut-off that depends on the exact number.

> No reason to have a subsonic flight that is gated by a supersonic flight, should we?

X-Planes (Low) isn't gated by anything.  (Except "First Launch".)  So I think that one is fine as it is.  It doesn't pay very much and the crew recuperation time prevents abusing it; it's basically a way to get paid for collecting flying-low-science from all your local biomes in a more controlled way than flinging Aerobees at them.  Also, planes that do it tend to be STOL enough to cope with the Runway.  Please don't take it away.

**Comment by norcalplanner** [comment]
> > Can you think of a way to inform the player that they are at x number of launches?
> 
> Why do they need informing it? All that happens is that the payouts start shrinking, there's never a hard cut-off that depends on the exact number.

Perhaps just update the contract description.  Just how some contracts will say "This contract may be completed 4 times" put in language to the effect of "Contract payout amounts will slowly decrease the more times this contract is completed."

**Comment by norcalplanner** [comment]
Quick thought on the satellite having sufficient power - how about just making it a requirement that the satellite contain X amount of EC onboard, with X being approximately what a probe core would use up in 3 hours?

**Comment by ec429** [comment]
@norcalplanner trouble with that is that something like Explorer 1 uses less than 1% the power that the SR core does.  There may well be reasonable satellites that have less EC than the SR.

**Comment by MikeOnTea** [comment]
> Re the sounding rockets, I still don't see why we can't just have a "decrease payout based on # of SRs completed" to replace the current "decrease payout on # of techs"; it seems like much less work for us than what you're proposing. Having read through all the discussion on Discord I don't recall seeing any reason why that wouldn't solve everything.

It's probably still worthwhile to decrease payouts as long as we have endless contracts. It could also fix the problem by itself if we do it drastically. Limiting the contracts to x per tech level might be similarly possible and an alternative though. I guess we should come up with either contract and try it out.

The problem/challenge with only decreasing payouts is that it needs to be a sharp decrease so that they still turn in profit in the beginning, but after let's say 10-20 contracts, you actually lose money when you do them. Then we could make it so that new tech levels increase payouts by offering more profitable contracts, which maybe also require more payload or a higher altitude.

**Comment by ec429** [comment]
@MikeOnTea you don't necessarily have to _lose_ money; just not make as much as you would using the same build time for satellites.

**Comment by MikeOnTea** [comment]
Once you're in satellite era, that might be true. But even then, you could steadily grind them on top of the sat contracts to get money... so, i probably think you should eventually lose money, or the contracts should disappear altogether.

**Comment by NathanKell** [comment]
Talking about both SR contracts and first orbit made me consider a Modest Proposal (tm).

No more SR contracts after First Orbital.

Now, hear me out (although I hasten to add: I am not convinced by this idea, I am merely proposing it).

The reasoning is thus. It *should* be possible, IMO, to reach orbit with 1950 tech, if you throw enough of it at it. Yes, go ahead, put that SR core in orbit. Heck, put lead ballast in orbit. But your penalty for doing so is you should now be expected to do something better. Except...you can't. Because you shot your wad on doing it early. So then you have to survive without funds for a while until you get enough tech to complete the actual satellite contracts.
By contrast, if you take it slow, you don't get the early infusion of cash (especially the RIS cash) but you do get a much more sustainable infrastructure and (on balance) more funds.

So then the choice becomes, time vs. money.

Now, what that doesn't solve is having a cheap, simple contract to use during 'down times'. But the more I think about it, the more I think this is a more meaningful choice than what we have now.

**Comment by NathanKell** [comment]
The less extreme version of this is swapping to the 3-6month cooldown version Pap mentioned after first orbital

**Comment by NathanKell** [comment]
@leudaimon brings up a fair point in discord--what's to prevent you grinding once the contract is accepted? So modify the proposal: no more SR contracts once you *accept* First Orbital, not once you complete it.

**Comment by leudaimon** [comment]
Following up on my suggestion, I agree with @NathanKell last idea, but still think the standard repeatable SR contracts must be nerfed. Besides, I think it would be fine to keep altitude and (if possible to implement) downrange distance contracts, as long as they always increase their requirements they are hard to abuse, and help the player make a gradual progression towards orbit capable vehicles.

**Comment by NathanKell** [comment]
Submitted a commit to clamp SR payouts, add cooldowns, and kill all SR contracts on accept of First Orbit.

I think that takes care of the SR portion of this, but that still leaves the rest of the early game. For that I made an issue on CBK about display mode--if CBK can support changing conics mode with TS level, we can start with no orbit lines displayed, then move to showing them with no patches, etc.. https://github.com/sarbian/CustomBarnKit/issues/6

Combine that, and the ideas we're tossing around on avionics, and I think the early game will be ok.

**Comment by pap1723** [comment]
Updated with a whole new idea that I believe has the most merit as far as being a good progression and still being friendly to less experienced players.

**Comment by Bornholio** [comment]
My new stupid idea, make SR contracts to test various general pieces of equipment, not quite the dumb Stock ones but close.  make one to three contracts per node, have them activate after each node is earned.

**Comment by NathanKell** [comment]
Looked through the revised proposal.

Tbh I'm not sure I'm that enamored of it--need to dwell on it for a bit more to think about it. I'm worried the early game will feel fairly sterile under these circumstances.

I like the downrange requirement, and think it adds some needed variety. But I'm not so sold on the drastic decrease of repeatables. Maybe there should be a single altitude SR repeatable and a single downrange SR repeatable? Both based off whatever your last record was, and when you accept First Orbit they go away.

**Comment by MikeOnTea** [comment]
> Maybe there should be a single altitude SR repeatable and a single downrange SR repeatable? Both based off whatever your last record was, and when you accept First Orbit they go away.

That could incentivize people to stay below a record again or only slightly increase it to milk the contracts? Especially for downrange contracts, larger steps make sense in my mind, your aim is to get to orbit eventually, so after having achieved let's say 1000 km, why bother with something like 1100? go for 2000 next.

The drastic decrease of repeatables has a big advantage: the non repeatable contracts with rapidly increasing difficulties don't require a cooldown i think, which we all know are somewhat of a hassle to deal with.

**Comment by leudaimon** [comment]
I also see no reason to stop the records (and by consequence the progression in the payload contract) for altitude and and distance at the milestone values. I think these can go up higher, pushing the envelope of the repeatable payload contract further. These contracts would only disappear once you accept first orbit, so if the player wants to linger for longer before accepting first orbit, they will have something to do - the payload contracts. 
One possibility I just thought about is that instead of the cooldowns, you can have a (low) maxcompletions for each level of the altitude/downrange records. The easy way to implement would be to have a contract for each level, with the given maxcompletions and disapeearing once you reach the next record - but I hope CC has a way to automate this.

**Comment by NathanKell** [comment]
Let's step back for a sec and talk about what goals we have for the early game. I think that'll hopefully get us more on the same page?

* Players should have some idea of how to progress.
* Players should never feel like their only alternative is "warp until a bunch of stuff unlocks" or "warp until 200 days of LV construction completes" or ditto for buildings.
* We still want to start in 1951.
* We don't want time to advance too fast (on moderate, the old hard, let's claim maybe 4-5 years of ingame time until first orbit would be great, but I'll settle for 3.)
* We don't want the player's challenges until orbit to be repetitive.
* We don't want the contracts present to be grindy or cheatable (i.e. where you under-perform so as not to lose later contracts).

That sound about right?

Now, at an even higher level, IMO RP-1 is a combination of three games:
* A program management sim (the high level decision making, the low level contract/tech/etc choices)
* A vehicle design sim (how you design vehicles to meet those specific goals given the stuff you have)
* A flight sim (how you fly what you got).
Obviously these all feed into each other.
But I mention this because we want the early game (just as we want all the game) to give interesting choices (and interesting areas for failure/learning, as well as just divergent paths) in all three areas. We don't want there to be one right high-level path to orbit; we don't want the player to only need to build one (or three) vehicles until orbit; and we don't want everything to fly the same.


Now, coming back to the issue at hand. I worry that we're focusing a bit too much on guiding the player, and removing the possibility of grinding/minmaxing/CHEATERRRing, and focusing a bit too little on what we might lose (interesting challenges for the player before orbit).  That said, I've been soundly persuaded in favor of having downrange contracts because they *diversify*, rather than constrict, the early experience--they are another challenge for the player to handle, on top of just shooting things up until orbit. But IMO they should work similarly to the existing SR system, in that the payload and downrange requirements should vary, although over time both should increase.

So my quick sketch proposal might be something like two mini-milestones, as y'all have suggested (2000km up, 4000km downrange, or whatever), in addition to two repeatables (Sounding Rocket, Downrange Rocket) each of which use an increasing range/weight metric to keep LV designs in flux as you gradually get more capable.

I would still shut down both when you accept First Orbit, however.

Now, the one other concern we have, that I didn't mention above, is making historical paths viable. As @Theysen points out, the Soviet approach is no longer viable, the pad upgrades take too long / cost too much, given the increased entry costs/tooling costs. Here I'm not super sure what to do--maybe the Soviet historical approach can't be made viable except on Normal or easier, although adding extra mini-milestones early will help since it'll draw money out of FO for earlier upgrades.

**Comment by NathanKell** [comment]
OH! Other things we haven't talked about, for slowing things down:
* Have a larger fixed-cost BP for vehicles, so SRs never build too fast even when cheap.
* Lower starting R&D rate quite a bit (5sci/year down to 1sci/year) but maybe make the curve affecting increase-from-upgrades less crippling.
* Something similar for build rates?

**Comment by NathanKell** [comment]
Last? thought for now--Discord talked about reliability revisiting. I firmly support this, along with much less pleasant airlighting curves for early engines. We need to be careful not to make things too frustrating (so might decrease build rates rather than increase failures, for slowdown purposes, beyond a certain point?) but in particular this makes sense to lower the use of airlighting.

It should also not be *too* hard (@ec429  ?) to add support to TF to detect what other engines are running while a given engine is running, and decrease reliability based on proximity. That will, sadly, be slow, but it will hopefully only be necessary until like 1958 or so, so it shouldn't be too much of a bugbear. In that way we could simulate the lower reliability of clusters. I also strongly support adding a little bit of variability to startup transients which might unbalance clusters without TVC.

**Comment by Standecco** [comment]
To make the Soviet approach viable we could offer 1 more *alternative* "first orbit" contract that offers more money in advance but requires to put a heavy payload in orbit. It wouldn't necessarily be historical but it would allow the player to develop the infrastructure needed for the much superior R-7. The player could also wait for better US alternatives if he doesn't feel like going to orbit with the vanguard or similar. This probably needs that engine clustering Nerf and making it clear that it's one or other in the contract description.

**Comment by theonegalen** [comment]
With regards to the US vs. Soviet approach, this could be set up as something from the administration building using Strategia.

**Comment by pap1723** [comment]
In progress, but most of what is on here has been implemented, or a new solution has been found.
