### ISSUE TITLE
Procedural avionics overhaul

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-0#968]
These ideas assume the general avionics overhaul that has been discussed in Discord is happening, so that we will have avionics models with different capabilities in different tech levels.

Similarly to the current system, we have tech tiers and booster, upper and probe avionics.
Also similar, I would make the part a procedural "tank" or something similar (hopefully with more options shape-wise)
I would ditch the utilization slider though, and do things in a similar way to RCS engines:

1. Separate parts for booster, upper and probe to make the UI simpler
2. For a given part, you choose the type of avionics module you want.
    * This part will have a set of capabilities (as per discussions on general avionics changes, and more ideas below).
    * It will also have a base mass, built-in battery and controllable mass capability (I guess we will keep controllable mass, right?).
    * You have a slider to increase the controllable mass above the baseline for the current tech level, and this increases part mass and energy consumption.
3. Each type - booster, upper and probe have different possible modules, base mass and mass/controllable mass ratio and EC consumption.
    * Boosters and Uppers would have the kinds of ascent guidance that have been discussed - pitch rate, PVG, etc.
    * Boosters should have no orbital manoeuvring capability.
    * For probes, I would add the option of science core only, without controllable mass, for lower power consumption and mass (and make the first Tech level have only this option).
4. In addition to the module (in the RCS GUI analogy that would be the fuel type), each part has a tech level (also similar to RCS), that improves the mass and consumption efficiency.
    * Similar to RCS, different module types are available at different techs (but most types should be available in the earlyish game), and the improvement of tech levels happens along the whole tech tree.

Other idea that would be nice to implement but I think may be more difficult:
Once you have that "core" part of the probe defined, it is determined to occupy a given volume, the remaining volume is turned into a service module tank. 
 * For this idea to work, the part would have to "find" which is the highest service module level unlocked so far
 * For booster and uppers, I would maybe limit this spare volume to be used for a battery.
 * For probe cores, it would be nice that RCS fuel could also be added.
 * Same thing for Payloads - added only to probe cores.
 * Even nicer would be to have the ability to add already unlocked experiments to the probe cores - but definitely not necessary.
    
The reason I'm suggesting to ditch the utilization slider is to make it more simple (aside from the fact it is currently very broken anyway), and given the more complex nature of this new avionics system I think it will be bloated with one more variable.

I don't think I can help with creating the system, but I sure can help with configs and balancing.

**Comment by Bornholio** [comment]
1. Make sure a depreciated part is left in maybe orphaned to carry current games ahead
2. sounds awesome and deep.  would need a lot of lamont time is my guess. 
3. sounds perfect.  might stop the battery in first node argument.
4.  will this fix the other proc weirdness with updating across devices? hmm

my dum idea of a consumable resource for avionics, especially lower stage high power. is have a hydraulic fluid type resource. Helium is a good choice as it is actually used (aerobee---Falcon 9)

Maybe just a three state Cheap/Normal/Expensive toggle.  or even a two state Commercial/Specialist  for optimization.

**Comment by MikeOnTea** [comment]
About the utilization slider - i don't know. I don't think it makes the UI too complicated, but i don't know whether we actually want to have it for gameplay/historic reasons, either.
Science Experiments would be cool and a distinctive feature for the probe core i guess.

I also wonder whether we should be rebalancing the current avionics first compared to the non proc ones, which we would have to do anyway, except if we want to adapt/remove non proc avionics later, aswell.

**Comment by leudaimon** [comment]
The problem is that the current implementation of the utilization slider is impossible to balance. It is based on quadratic equations with different curves for price and tonnage. So depending on the configs there will be an "optimum" price/tonnage utilization value. For some of the current configs (which were balanced with 100% utilization in mind) this optimum is above 100%, which means you get a cheaper part with, say, 120% than 100% utilization for a given tonnage.
With regard to historic reasons, I also don't feel it's a specially accurate mechanic, and all the changes we are gonna do to avionics in general will bring it much closer to realism anyway.

**Comment by thesciencenut** [comment]
Would it be possible to add in tanks for the probe core option just as the stock probe cores have?

It would be nice to have the ability to use less parts and to have everything all in one place

**Comment by pap1723** [comment]
@thesciencenut that is the eventual long term goal of Proc Avionics. Soon(TM)

**Comment by MikeOnTea** [comment]
Repost of my plots for a possible future root based avionics mass scaling. Plotted are the lunar tech level in solid lines and the vanguard tech level in dotted lines. Also plotted are three reference avionics with their masses and vessel masses, Vanguard, Atlas/Centaur, and Saturn V. First plot with normal axes, which makes the small values very cramped but just to understand what's going on:
![image](https://user-images.githubusercontent.com/11480934/54160094-e9133a00-444e-11e9-8dbe-a74c95af409a.png)
Second, the same plot with both axes plotted logarithmically, small values are much better visible here:
![image](https://user-images.githubusercontent.com/11480934/54160550-288e5600-4450-11e9-8cd3-c698bb7059bc.png)
As can be seen in this graph, for the lunar tech i just use Atlas/Centaur and the S-V avionics as combined reference, whereas previously one was used as a refrence for upper stage avionics, the other for booster avionics. Other tech levels could just be linearly scaled like was previously done, as can be seen for the vanguard tech levels which are just linearly scaled versions of the lunar tech levels.
Using such root based scaling, the dependence on mass is much less pronounced, small LV avionics will get comparably heavier (disregarding minimum controllable masses which set a lower bound on avionics mass) and large LV avionics will get comparatively lighter.

**Comment by MikeOnTea** [comment]
As an update i've implemented the proposal for testing. The previous avionics configurations get replaced by Near-Earth and Deep-Space. Remaining volume is turned into a service module tank, even thought his is still generic and not the SM-1 to 4 levels. Avionics requires tooling now and got more expensive in general.
Currently the balance compared to the old looks like this:
![image](https://user-images.githubusercontent.com/11480934/60758775-6fb1df80-a01b-11e9-9ee4-8e1cca5af78e.png)

**Comment by siimav** [comment]
Done and released

**Comment by MikeOnTea** [comment]
Some little follow up documentation. Deep space avionics have an additional shielding mass component in their total mass. This is both for balancing purposes (to give them a disadvantage compared to near earth avionics) but also somewhat realistic. Deep space avionics are supposed to represent basic systems/components of deep space probes, which usually have some kind of passive thermal/radiation shielding. Mariner 4, for example, [contained 8 lb of passive aluminum shielding/a thermal control subsystem of 15 lb](https://ntrs.nasa.gov/api/citations/19670005554/downloads/19670005554.pdf). Not sure if there really was much technical progress here, though Juno used [titanium](https://en.wikipedia.org/wiki/Juno_Radiation_Vault).

# Calculation
```Shielded mass = electronics mass ^ (2/3) * shielding mass factor```

The power of 2/3 is used to convert the mass scaling into a surface scaling (a cube with 8 times the volume/mass of a reference cube has 4 times the surface of this cube, 8^(2/3) = 4). The shielding mass factor is now just a factor to determine how much shielding mass is required for a certain electronics container surface. 0.1 was probably a very rough initial value which could probably be refined by collecting some more probes' shielding mass and compare it with their electronics mass. 

Let's try this calculation for mariner 4 and relevant part masses:

| Part        | Weight (lb)  |
| -----------------------|------:|
| Central Computer     | 11.4 |
| Command                 | 10.1 |
| Data Encoder            | 22.4 |
| Guidance & Control  | 63.3 |
| Sum w/o guidance    | 43.9 |
| Sum with guidance   | 107.2 |
| Total spacecraft         | 574.7|

So with a weight of 43.9 lb we get a calculated shield mass of 1.2 lb, quite a bit lower than the real mass of 8 lb.
Using 107.2 lb, we get 2.3 lb of calculated shield mass, still quite a bit lower than the real mass.
You could argue some of these shields shield components that are not modeled by our avionics module.
However, even when using the total spacecraft weight, we only get to a calculated shield weight of 6.9 lb, still lower than the real weight.
In the end it's hard to get good data for spacecraft and to decide how to model this in the game.
It wouldn't surprise me though if KSP procedural avionics probes had lower weights than their real world counterparts, and if that's the case we probably should turn up those modifiers representing things like structural/shielding mass instead of turning them down or removing them. :)

**Comment by Clayell** [comment]
Thanks for the info! I would also suggest that the shieldingMassFactor decreases with increasing tech, but I do not feel like hunting down all of the sources required for that.
