### ISSUE TITLE
Satellite contract issues

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#990]
Noticed that some of the early-mid weather contracts need a rebalance, saw a harder contract (sun-synch, IIRC) contract paying less than an easier one (Second-gen I think?).

Probably need to do a pass on them all just to spot-check.

**Comment by lpgagnon** [comment]
Is that necessarily a problem? 2nd gens have a max repeat count; I had supposed the idea was that those were still high-paying experimental ones, while sun-sync (infinitely repeatable) represents more routine launches.

**Comment by Bornholio** [comment]
My experience this last early run.  take with grain of salt.  Once first orbit and one other orbit was complete it was basically a wait till solar panels and even prioritizing that was still a year of fast forward with no contracts to do except supersonic flights.  Its a long wait to manned SO at this same time so.  So my entire contract availability was [first solar, manned SO, lunar impact, lunar orbit and lunar landing]  

After Solar those other contract are definitely need some payout balance, agree heartily. Running with pap's latest changes now to see what stoppers are there.  Several, like Geo are well beyond my tech capability because I've rushed to solar. So its also a slightly barren area but at least there are options to do. Altogether starting to meet the longer time frame expectations.

Obviously it only takes a few techs to make orbit if you know how. For newer people i'm guessing hard would result in orbit in '56 range unless they have experience rushing.  Still an incentive to hold on to SR contracts and keep focusing on earning a few extra points. RO newb's are gonna wonder why its taking so long :)

**Comment by pap1723** [comment]
This was a concern of mine as we were talking about the changes. What to do after First (and Second) Orbit. I think that adding a set of contracts that are available after (Second) orbit and before First Solar is complete is a good idea.

These would be the additional follow-up satellites that were sent. For the US it was the Explorer series and for the Soviets, it was the additional Sputniks as well. I have done some reading on the Batteries used at the time and it makes sense to change how they work. I will leave that for a different time as I explore some options with Kerbalism.

**Comment by NathanKell** [comment]
Agree on a few contracts before solar...

Sent by my thumbs, slowly.

**Comment by siimav** [comment]
All the sat contracts received a tuning in https://github.com/KSP-RO/RP-0/commit/28fed57e2663de4935398697344066049711328a
Closing this one even though the issue of not having any sat contracts between FO and First Solar is likely still there.
